export const CHARACTER_MAP = {
	'Qlipoth': 'Qlipoth',
	'Amber Lord': 'Qlipoth',
	'Firmamend Arbiter': 'Qlipoth',
	'Yaoshi': 'Yaoshi',
	'Sanctus Medicus': 'Yaoshi',
	'Plagues Author': 'Yaoshi',
	'Master of Immortality': 'Yaoshi',
	'Merciful Medicus': 'Yaoshi',
	'The Merciful One': 'Yaoshi',
	'Lan': 'Lan',
	'Reignbow Arbiter': 'Lan',
	'Fuli': 'Fuli',
	'Glowswather': 'Fuli',
	'Aha': 'Aha',
	'The Laughter': 'Aha',
	'Joyseeker': 'Aha',
	'Adrian Spencer Smith': 'Adrian Spencer Smith',
	'IX': 'IX',
	'All-Consuming Black Hole': 'IX',
	'Dark Sun': 'IX',
	'Pitch-Black Great Sun': 'IX',
	'Akivili': 'Akivili',
	'Cloudstrider': 'Akivili',
	'Ena': 'Ena',
	'HooH': 'HooH',
	'Idrila': 'Idrila',
	'Anne Duray': 'Idrila',
	'Goddess of Beauty': 'Idrila',
	'Wondergazer': 'Idrila',
	'Archer Lord of Fate': 'Lan',
	'Devilish Archer Author': 'Lan',
	'God of the Skybow': 'Lan',
	// 'Long': 'Long',
	'Progenitor of All Dragons': 'Long',
	'Mythus': 'Mythus',
	'Nanook': 'Nanook',
	'Ruin Author': 'Nanook',
	'Supreme Destroyer': 'Nanook',
	'Supreme Executioner': 'Nanook',
	'The Blemished One': 'Nanook',
	'Nous': 'Nous',
	'Droidhead': 'Nous',
	'Monarch of Myriad Machines': 'Nous',
	'Wisdomwalker': 'Nous',
	'Oroboros': 'Oroboros',
	'Tayzzyronth': 'Tayzzyronth',
	'Imperator Insectorum': 'Tayzzyronth',
	'Sand King': 'Tayzzyronth',
	'Swarm Author': 'Tayzzyronth',
	'Terminus': 'Terminus',
	'Xipe': 'Xipe',
	'Great One of Paradise': 'Xipe',
	'Thousand-Faced Great One': 'Xipe',
	'Triple-Faced Soul': 'Xipe',
	'Skaracabaz': 'Skaracabaz',
	'Doctor DeWitt': 'Doctor DeWitt',
	'Kolchis': 'Kolchis',
	'Qhaley': 'Qhaley',
	'Wen-II': 'Wen-II',
	'Zephyro': 'Zephyro',
	'Red-Nosed Old-Timer': 'Red-Nosed Old-Timer',
	'Sulank': 'Sulank',
	'Torkirk': 'Torkirk',
	'Talorensky': "Talorensky",
	'Rama': 'Rama',
	'Herta': 'Herta',
	'Emperor Rubert': 'Emperor Rubert',
	'Rubert I': 'Rubert I',
	'Rubert II': 'Rubert II',
	'Oswaldo Schneider': 'Oswaldo Schneider',
	'Oswaldo': 'Oswaldo Schneider',
	'Beatrice Mellanine': 'Beatrice Mellanine',
	'Stephen Lloyd': 'Stephen Lloyd',
	'Screwllum': 'Screwllum',
	'Ruan Mei': 'Ruan Mei',
	'Stoneblade': 'Stoneblade',
	'Baden Babbibalo Bala': 'Baden Babbibalo Bala',
	'Doctor Kray': 'Doctor Kray',
	'Alda': 'Alda',
	'Endin': 'Endin',
	'Dr. Riddle': 'Dr. Riddle',
	'Dr. Primitive': "Dr. Primitive",
	'Elias Salas': 'Elias Salas',
	'Louis Fleming': 'Louis Fleming',
	'Yu Qingtu': 'Yu Qingtu',
	'Titecie': 'Titecie',
	'Kayer': "Kayer",
	'Viropa': 'Viropa',
	'Celenova': 'Celenova',
	'Polka Kakamond': 'Polka Kakamond',
	'Talot': "Talot",
	'Eton': 'Eton',
	'Akbar': 'Akbar',
	'Slejka': 'Slejka',
	
	'Janus': 'Janus',
	'Gate of Infinity': 'Janus',
	'Passage Titan': 'Janus',
	'Talanton': 'Talanton',
	'Scale of Justice': 'Talanton',
	'Law Titan': 'Talanton',
	'Oronyx': 'Oronyx',
	'Veil of Evernight': 'Oronyx',
	'Time Titan': 'Oronyx',
	'Georios': 'Georios',
	'Pillar of Stone': 'Georios',
	'Earth Titan': 'Georios',
	'Phagousa': 'Phagousa',
	'Chalice of Plenty': 'Phagousa',
	'Ocean Titan': 'Phagousa',
	'Aquila': 'Aquila',
	'Eye of Twilight': 'Aquila',
	'Sky Titan': 'Aquila',
	'Kephale': 'Kephale',
	'Throne of Worlds': 'Kephale',
	'Worldbearing Titan': 'Kephale',
	'Cerces': 'Cerces',
	'Bough of Rift': 'Cerces',
	'Reason Titan': 'Cerces',
	'Mnestia': 'Mnestia',
	'Chrysalis of Gold': 'Mnestia',
	'Romance Titan': 'Mnestia',
	'Nikador': 'Nikador',
	'Lance of Fury': 'Nikador',
	'Strife Titan': 'Nikador',
	'Thanatos': 'Thanatos',
	'Hand of Shadow': 'Thanatos',
	'Death Titan': 'Thanatos',
	'Zagreus': 'Zagreus',
	'Coin of Whimsy': 'Zagreus',
	'Trickery Titan': 'Zagreus',
	
	'Aglaea': 'Aglaea',
	'Avsha': 'Avsha',
}

export const FACTION_MAP = {
	'The Architects': 'The Architects',
	'Memokeeper': 'Garden of Recollection',
	'Memokeepers': 'Garden of Recollection',
	'Self-Annihilator': 'Self-Annihilators',
	'Self-Annihilators': 'Self-Annihilator',
	'Galaxy Rangers': 'Galaxy Rangers',
	'Galaxy Ranger': 'Galaxy Rangers',
	'Elixir Seekers': 'Elixir Seekers',
	'Elixir Seeker': 'Elixir Seekers',
	'Nailscrap Town': 'Nailscrap Town',
	'Memosnatcher': 'Memosnatchers',
	'Memosnatchers': 'Memosnatchers',
	'Bavelli-3': 'Bavelli-3',
	'Omen Vanguard': 'Omen Vanguards',
	'Mechanical City': 'Mechanical City',
	'Talia': 'Talia',
	'Lord Ravager': 'Lord Ravager',
	'Doctor of Chaos': 'Doctors of Chaos',
	'Doctors of Chaos': 'Doctors of Chaos',
	'Sin Thirster': 'Sin Thirster',
	'Sin Thirsters': 'Sin Thirster',
	'Annihilation Gang': 'Annihilation Gang',
	'Ever-Flame Mansion': 'Ever-Flame Mansion',
	'Jepella Brotherhood': 'Jepella Brotherhood',
	'Punklorde': 'Punklorde',
	'Capital of Passion': 'Capital of Passion',
	'The Swarm': 'The Swarm',
	'Interastral Peace Corporation': 'Interastral Peace Corporation',
	'IPC': 'Interastral Peace Corporation',
	'Jepella': 'Jepella',
	'Houyhnhnm': 'Houyhnhnm',
	'Borisin': 'Borisin',
	'The Cremators': 'The Cremators',
	'Firesmith Clan': 'Firesmith Clan',
	'Firesmiths': 'Firesmith Clan',
	'Firesmith': 'Firesmith Clan',
	'Pepeshi': 'Pepeshi',
	'Pepeshis': 'Pepeshi',
	'History Fictionologists': 'History Fictionologists',
	'History Fictionologist': 'History Fictionologists',
	'Astral Ecology School': 'Astral Ecology School',
	'Muldrasil': 'Muldrasil',
	'Wingweavers': 'Wingweaver',
	'Wingweaver': 'Wingweaver',
	'Interastral Culinary Association': 'Interastral Culinary Association',
	'Lapispeakers': 'Lapispeakers',
	'Lapispeaker': 'Lapispeakers',
	'Penacony': 'Penacony',
	'Land of the Dreams': 'Penacony',
	'Masked Fools': 'Masked Fools',
	'Masked Fool': 'Masked Fools',
	'Intelligentsia Guild': 'Intelligentsia Guild',
	'Galactic Rescue Team': 'Galactic Rescue Team',
	'Beyond the Sky Choir': 'Beyond the Sky Choir',
	'Shadow of IX': 'Shadow of IX',
	'Shadows of IX': "Shadow of IX",
	'Charon-Targin System Alliance': "Charon-Targin System Alliance",
	'Omen Vanguards': 'Omen Vanguards',
	'Business Consolidation Department': 'Business Consolidation Department',
	'Creed Exequy': 'Creed Exequy',
	'Stellaron Hunters': 'Stellaron Hunters',
	'Stellaron Hunter': 'Stellaron Hunters',
	'The Riddlers': 'The Riddlers',
	'Leviathans': 'Leviathan',
	'Leviathan': 'Leviathan',
	'Technology Department': 'Technology Department',
	'The Nameless': 'The Nameless',
	'Nameless': 'The Nameless',
	'Device IX': 'Device IX',
	'Mourning Actors': 'Mourning Actors',
	'Mourning Actor': 'Mourning Actors',
	'Knight of Beauty': 'Knights of Beauty',
	'Knights of Beauty': 'Knights of Beauty',
	'Laurel Wreath': 'Laurel Wreath',
	'Black Forest': 'Black Forest',
	'The Family': 'The Family',
	'Bounty Hunter': 'Bounty Hunters',
	'Bounty Hunters': 'Bounty Hunters',
	'Antimatter Legion': 'Antimatter Legion',
	'New Londinium': 'New Londinium',
	'Armed Archaeologists': 'Armed Archaeologists',
	'Mirror Holders': 'Mirror Holders',
	'Mirror Holder': 'Mirror Holders',
	'Genius Society': 'Genius Society',
	'Zimander Federation': 'Zimander Federation',
	'Merlo Nebula': 'Merlo Nebula',
	
	'Okhema': 'Okhema',
}

export const MENTION_MAP = {
	...CHARACTER_MAP,
	...FACTION_MAP
}

export function getMentionsWithMap(texts: string[], map: Record<string, string>) {
	const mentions = new Set<string>()

	for (let text of texts) {
		for (const [keyword, mention] of Object.entries(map)) {
			const regexp = new RegExp(`\\b${keyword}\\b`, 'g')
			if (regexp.test(text)) {
				mentions.add(mention)
				text.replaceAll(regexp, ' ')
			}
		}
	}

	return [...mentions.values()].sort()
}

export function getMentions(...texts: string[]) {
	return getMentionsWithMap(texts, MENTION_MAP)
}

export function getFactionMentions(...texts: string[]) {
	return getMentionsWithMap(texts, FACTION_MAP)
}

export function getCharacterMentions(...texts: string[]) {
	return getMentionsWithMap(texts, CHARACTER_MAP)
}