export const wikiPageMap: Record<string, {pagename: string}> = {
	['item_"Faded Sun"']: { pagename: '"Faded Sun"' },
	['item_\'\'A Letter of Unknown Origin\'\'']: { pagename: 'A Letter of Unknown Origin' },
	['item_\'\'Manuscript of Delirium\'\'']: { pagename: 'Manuscript of Delirium' },
	['item_\'\'Manuscript of Silence\'\'']: { pagename: 'Manuscript of Silence' },
	['item_\'\'Manuscript of Wisdom\'\'']: { pagename: 'Manuscript of Wisdom' },
	['item_11']: { pagename: 'Trailblaze Power' },
	['item_12']: { pagename: 'Reserved Trailblaze Power' },
	['item_25']: { pagename: 'The Returning Trail' },
	['item_51']: { pagename: 'The Nameless EXP' },
	['item_235']: { pagename: 'Relic Remains' },
	['item_236']: { pagename: 'Self-Modeling Resin' },
	['item_271']: { pagename: 'Superimposer (Custom-made)' },
	['item_503']: { pagename: 'Herta Bond' },
	['item_800']: { pagename: 'First Voyage\'s Blessing' },
	['item_1']: { pagename: 'Stellar Jade' },
	['item_101']: { pagename: 'Star Rail Pass' },
	['item_102']: { pagename: 'Star Rail Special Pass' },
	['item_11001']: { pagename: 'March 7th\'s Eidolon' },
	['item_11002']: { pagename: 'Dan Heng\'s Eidolon' },
	['item_11003']: { pagename: 'Himeko\'s Eidolon' },
	['item_11004']: { pagename: 'Welt\'s Eidolon' },
	['item_11005']: { pagename: 'Kafka\'s Eidolon' },
	['item_11006']: { pagename: 'Silver Wolf\'s Eidolon' },
	['item_11008']: { pagename: 'Arlan\'s Eidolon' },
	['item_11009']: { pagename: 'Asta\'s Eidolon' },
	['item_110101']: { pagename: 'Tears of Dreams' },
	['item_110111']: { pagename: 'Shattered Blade' },
	['item_110112']: { pagename: 'Lifeless Blade' },
	['item_110113']: { pagename: 'Worldbreaker Blade' },
	['item_110121']: { pagename: 'Arrow of the Beast Hunter' },
	['item_110122']: { pagename: 'Arrow of the Demon Slayer' },
	['item_110123']: { pagename: 'Arrow of the Starchaser' },
	['item_11013']: { pagename: 'Herta\'s Eidolon' },
	['item_110131']: { pagename: 'Key of Inspiration' },
	['item_110132']: { pagename: 'Key of Knowledge' },
	['item_110133']: { pagename: 'Key of Wisdom' },
	['item_110141']: { pagename: 'Endurance of Bronze' },
	['item_110142']: { pagename: 'Oath of Steel' },
	['item_110143']: { pagename: 'Safeguard of Amber' },
	['item_110151']: { pagename: 'Obsidian of Dread' },
	['item_110152']: { pagename: 'Obsidian of Desolation' },
	['item_110153']: { pagename: 'Obsidian of Obsession' },
	['item_110161']: { pagename: 'Harmonic Tune' },
	['item_110162']: { pagename: 'Ancestral Hymn' },
	['item_110163']: { pagename: 'Stellaris Symphony' },
	['item_110171']: { pagename: 'Seed of Abundance' },
	['item_110172']: { pagename: 'Sprout of Life' },
	['item_110173']: { pagename: 'Flower of Eternity' },
	['item_110181']: { pagename: 'Borisin Teeth' },
	['item_110182']: { pagename: 'Lupitoxin Sawteeth' },
	['item_110183']: { pagename: 'Moon Madness Fang' },
	['item_110211']: { pagename: 'Scattered Stardust' },
	['item_110212']: { pagename: 'Crystal Meteorites' },
	['item_110213']: { pagename: 'Divine Amber' },
	['item_110221']: { pagename: 'Fiery Spirit' },
	['item_110222']: { pagename: 'Starfire Essence' },
	['item_110223']: { pagename: 'Heaven Incinerator' },
	['item_110231']: { pagename: 'Firmament Note' },
	['item_110232']: { pagename: 'Celestial Section' },
	['item_110233']: { pagename: 'Heavenly Melody' },
	['item_110241']: { pagename: 'Alien Tree Seed' },
	['item_110242']: { pagename: 'Nourishing Honey' },
	['item_110243']: { pagename: 'Myriad Fruit' },
	['item_110400']: { pagename: 'Enigmatic Ectostella' },
	['item_110401']: { pagename: 'Broken Teeth of Iron Wolf' },
	['item_110402']: { pagename: 'Endotherm Chitin' },
	['item_110403']: { pagename: 'Horn of Snow' },
	['item_110404']: { pagename: 'Lightning Crown of the Past Shadow' },
	['item_110405']: { pagename: 'Storm Eye' },
	['item_110406']: { pagename: 'Void Cast Iron' },
	['item_110407']: { pagename: 'Golden Crown of the Past Shadow' },
	['item_110411']: { pagename: 'Netherworld Token' },
	['item_110412']: { pagename: 'Searing Steel Blade' },
	['item_110413']: { pagename: 'Gelid Chitin' },
	['item_110414']: { pagename: 'Shape Shifter\'s Lightning Staff' },
	['item_110415']: { pagename: 'Ascendant Debris' },
	['item_110416']: { pagename: 'Nail of the Ape' },
	['item_110417']: { pagename: 'Suppressing Edict' },
	['item_110422']: { pagename: 'Raging Heart' },
	['item_110423']: { pagename: 'Dream Fridge' },
	['item_110426']: { pagename: 'Dream Flamer' },
	['item_110501']: { pagename: 'Destroyer\'s Final Road' },
	['item_110502']: { pagename: 'Guardian\'s Lament' },
	['item_110503']: { pagename: 'Regret of Infinite Ochema' },
	['item_110504']: { pagename: 'Past Evils of the Borehole Planet Disaster' },
	['item_111001']: { pagename: 'Extinguished Core' },
	['item_111002']: { pagename: 'Glimmering Core' },
	['item_111003']: { pagename: 'Squirming Core' },
	['item_11101']: { pagename: 'Bronya\'s Eidolon' },
	['item_111011']: { pagename: 'Thief\'s Instinct' },
	['item_111012']: { pagename: 'Usurper\'s Scheme' },
	['item_111013']: { pagename: 'Conqueror\'s Will' },
	['item_11102']: { pagename: 'Seele\'s Eidolon' },
	['item_11103']: { pagename: 'Serval\'s Eidolon' },
	['item_11104']: { pagename: 'Gepard\'s Eidolon' },
	['item_11105']: { pagename: 'Natasha\'s Eidolon' },
	['item_11106']: { pagename: 'Pela\'s Eidolon' },
	['item_11107']: { pagename: 'Clara\'s Eidolon' },
	['item_11108']: { pagename: 'Sampo\'s Eidolon' },
	['item_11109']: { pagename: 'Hook\'s Eidolon' },
	['item_11110']: { pagename: 'Lynx\'s Eidolon' },
	['item_11111']: { pagename: 'Luka\'s Eidolon' },
	['item_11112']: { pagename: 'Topaz and Numby\'s Eidolon' },
	['item_112001']: { pagename: 'Silvermane Badge' },
	['item_112002']: { pagename: 'Silvermane Insignia' },
	['item_112003']: { pagename: 'Silvermane Medal' },
	['item_11201']: { pagename: 'Qingque\'s Eidolon' },
	['item_112011']: { pagename: 'Ancient Part' },
	['item_112012']: { pagename: 'Ancient Spindle' },
	['item_112013']: { pagename: 'Ancient Engine' },
	['item_11202']: { pagename: 'Tingyun\'s Eidolon' },
	['item_11203']: { pagename: 'Luocha\'s Eidolon' },
	['item_11204']: { pagename: 'Jing Yuan\'s Eidolon' },
	['item_11205']: { pagename: 'Blade\'s Eidolon' },
	['item_11206']: { pagename: 'Sushang\'s Eidolon' },
	['item_11207']: { pagename: 'Yukong\'s Eidolon' },
	['item_11208']: { pagename: 'Fu Xuan\'s Eidolon' },
	['item_11209']: { pagename: 'Yanqing\'s Eidolon' },
	['item_11210']: { pagename: 'Guinaifen\'s Eidolon' },
	['item_11211']: { pagename: 'Bailu\'s Eidolon' },
	['item_11212']: { pagename: 'Jingliu\'s Eidolon' },
	['item_11213']: { pagename: 'Dan Heng • Imbibitor Lunae\'s Eidolon' },
	['item_11214']: { pagename: 'Xueyi\'s Eidolon' },
	['item_11215']: { pagename: 'Hanya\'s Eidolon' },
	['item_11217']: { pagename: 'Huohuo\'s Eidolon' },
	['item_113001']: { pagename: 'Immortal Scionette' },
	['item_113002']: { pagename: 'Immortal Aeroblossom' },
	['item_113003']: { pagename: 'Immortal Lumintwig' },
	['item_11301']: { pagename: 'Gallagher\'s Eidolon' },
	['item_113011']: { pagename: 'Artifex\'s Module' },
	['item_113012']: { pagename: 'Artifex\'s Cogwheel' },
	['item_113013']: { pagename: 'Artifex\'s Gyreheart' },
	['item_11302']: { pagename: 'Argenti\'s Eidolon' },
	['item_11303']: { pagename: 'Ruan Mei\'s Eidolon' },
	['item_11305']: { pagename: 'Dr. Ratio\'s Eidolon' },
	['item_11306']: { pagename: 'Sparkle\'s Eidolon' },
	['item_11307']: { pagename: 'Black Swan\'s Eidolon' },
	['item_11308']: { pagename: 'Acheron\'s Eidolon' },
	['item_11312']: { pagename: 'Misha\'s Eidolon' },
	['item_114001']: { pagename: 'Dream Collection Component' },
	['item_114002']: { pagename: 'Dream Flow Valve' },
	['item_114003']: { pagename: 'Dream Making Engine' },
	['item_114011']: { pagename: 'Tatters of Thought' },
	['item_114012']: { pagename: 'Fragments of Impression' },
	['item_114013']: { pagename: 'Shards of Desires' },
	['item_120000']: { pagename: 'Hertareum' },
	['item_120001']: { pagename: 'Shield (Item)' },
	['item_120002']: { pagename: 'Strale' },
	['item_120003']: { pagename: 'Clock Credits' },
	['item_121000']: { pagename: 'Lil\' Twisty Bubble Gum' },
	['item_121001']: { pagename: 'Exorcismal Fulu' },
	['item_122000']: { pagename: 'Aideen Tokens' },
	['item_140000']: { pagename: 'Praise of High Morals' },
	['item_140004']: { pagename: 'Ancient Coin' },
	['item_140017']: { pagename: 'Core Module' },
	['item_140021']: { pagename: 'Thermal-Powered Mechanical Mining Pick' },
	['item_140022']: { pagename: 'Anti-Dust Mask' },
	['item_140023']: { pagename: 'Customized Pink Safety Helmet' },
	['item_140033']: { pagename: 'Mine Cart Pin' },
	['item_140034']: { pagename: 'Robot Settlement Level 1 Certification' },
	['item_140035']: { pagename: 'Robot Settlement Level 2 Certification' },
	['item_140036']: { pagename: 'Robot Settlement Level 3 Certification' },
	['item_140039']: { pagename: 'Mine Cart Wheelset' },
	['item_140040']: { pagename: 'A Bottle of Glass Marbles' },
	['item_140066']: { pagename: 'Treasure Map' },
	['item_140067']: { pagename: 'Real Treasure Map' },
	['item_140069']: { pagename: 'Used Item Auction Pamphlet' },
	['item_140071']: { pagename: 'Ultra Nickel Part' },
	['item_140073']: { pagename: 'Blue Signal Log' },
	['item_140082']: { pagename: 'Milk Powder Package' },
	['item_140083']: { pagename: 'Anonymous Package' },
	['item_140084']: { pagename: 'Thousand Stars Access Authentication' },
	['item_140085']: { pagename: 'Access Authentication' },
	['item_140086']: { pagename: 'Corporate Access Authentication' },
	['item_140090']: { pagename: 'Box of Rubbing Alcohol' },
	['item_140091']: { pagename: 'Box of Special Painkillers' },
	['item_140095']: { pagename: 'Children\'s Book Package' },
	['item_140096']: { pagename: 'Toddler Clothing Package' },
	['item_140103']: { pagename: 'Commodity Contract' },
	['item_140104']: { pagename: 'Geomarrow Probe' },
	['item_140111']: { pagename: 'Rusted Key' },
	['item_140123']: { pagename: 'Backup Batteries' },
	['item_140125']: { pagename: 'Mei\'s Notes: Flowers' },
	['item_140126']: { pagename: 'Mei\'s Notes: Learning About Housework' },
	['item_140127']: { pagename: 'Mei\'s Testimony' },
	['item_140128']: { pagename: 'Testimony From the Clumsy Lady' },
	['item_140129']: { pagename: 'Testimony From the Suddenly Excited Man' },
	['item_140130']: { pagename: 'Cycrane Surveillance Images' },
	['item_140132']: { pagename: 'Master Capote\'s Fan Reply Card' },
	['item_140133']: { pagename: 'Master Capote\'s Limited-Edition Snapshot' },
	['item_140134']: { pagename: 'Master Capote\'s Life Wiki' },
	['item_140135']: { pagename: 'Arlan\'s ID Pass' },
	['item_140136']: { pagename: 'Broken Ceiling Tile' },
	['item_140137']: { pagename: 'Footprint' },
	['item_140138']: { pagename: 'Photo of Arlan\'s Back' },
	['item_140140']: { pagename: 'Damaged Music Box' },
	['item_140146']: { pagename: 'Package for Peak' },
	['item_140147']: { pagename: 'Package for Eunice' },
	['item_140148']: { pagename: 'Package With Illegible Recipient' },
	['item_140151']: { pagename: 'A Bouquet of Ball Peonies' },
	['item_140152']: { pagename: 'A Bunch of Rainbows' },
	['item_140153']: { pagename: 'A Bouquet of First Snow' },
	['item_140154']: { pagename: 'A Stalk of Marquise' },
	['item_140156']: { pagename: 'Golden Badge' },
	['item_140157']: { pagename: 'Disciples of Sanctus Medicus Letter' },
	['item_140158']: { pagename: 'Folded Photo' },
	['item_140159']: { pagename: 'Strange Prescription' },
	['item_140165']: { pagename: 'Language Module' },
	['item_140167']: { pagename: 'A Note Between Book Pages' },
	['item_140175']: { pagename: 'IPC Designer Invite' },
	['item_140177']: { pagename: 'Chengjie\'s Paper Boat' },
	['item_140182']: { pagename: 'Dirty Mechanical Part' },
	['item_140183']: { pagename: 'Old Tin Box' },
	['item_140184']: { pagename: 'A Bottle of Draconic Tears' },
	['item_140197']: { pagename: 'A Medicine Concocted by Dan Shu' },
	['item_140202']: { pagename: 'Ice-Fresh Raw Frostweave Salmon Slices' },
	['item_140203']: { pagename: 'Mimic Snow Slugs' },
	['item_140206']: { pagename: 'Geomarrow Activation Element' },
	['item_140207']: { pagename: 'Frostweave Salmon Bread' },
	['item_140209']: { pagename: 'Snow Plains Combo Stew' },
	['item_140212']: { pagename: 'Microfilm' },
	['item_140213']: { pagename: 'Dismantled Art Pieces' },
	['item_140215']: { pagename: 'Old Photo: Mechanism Energy Hub' },
	['item_140218']: { pagename: 'Treasure Map: Information Terminal and Display Monitor Set' },
	['item_140221']: { pagename: 'Jing Yuan\'s Memories' },
	['item_140222']: { pagename: 'Yukong\'s Exchange Diary' },
	['item_140223']: { pagename: 'Caiyi\'s Exchange Diary' },
	['item_140225']: { pagename: 'Compendium of Remedies (Item)' },
	['item_140229']: { pagename: 'Lost and Found Notice' },
	['item_140234']: { pagename: 'Auspicious XV' },
	['item_140237']: { pagename: 'Override Module' },
	['item_140238']: { pagename: 'Divine Arrow Embers' },
	['item_140239']: { pagename: 'Torn Manuscript Fragment' },
	['item_140240']: { pagename: 'A Mysterious Key' },
	['item_140242']: { pagename: 'A tuskpir wrap bought for Bailu' },
	['item_140243']: { pagename: 'A songlotus cake bought for Bailu' },
	['item_140244']: { pagename: 'Berrypheasant skewers bought for Bailu' },
	['item_140246']: { pagename: 'Mung bean soda bought for Bailu' },
	['item_140247']: { pagename: 'Courier Package' },
	['item_140248']: { pagename: 'Payment Record for Exhibits' },
	['item_140249']: { pagename: 'Dock Worker\'s Testimony' },
	['item_140250']: { pagename: 'Rent for Aurum Alley Dock' },
	['item_140251']: { pagename: 'Dock Lease Contract' },
	['item_140252']: { pagename: 'Aurum Alley Merchant Guild Turnover' },
	['item_140253']: { pagename: 'Artistry Hardware Sales Analysis' },
	['item_140254']: { pagename: 'Aurum Alley Historical Trading Volume' },
	['item_140255']: { pagename: 'Aurum Alley Merchant Guild Bidding Deposit' },
	['item_140256']: { pagename: 'Spices Supreme Crossover Event' },
	['item_140257']: { pagename: 'Aurum Alley Business Opinion Poll' },
	['item_140258']: { pagename: 'Guild Insignia Rubbing (I)' },
	['item_140259']: { pagename: 'Guild Insignia Rubbing (II)' },
	['item_140260']: { pagename: 'Guild Insignia Rubbing (III)' },
	['item_140261']: { pagename: 'Guild Insignia Rubbing (IV)' },
	['item_140262']: { pagename: 'Guild Insignia Rubbing (V)' },
	['item_140263']: { pagename: 'Guild Insignia Rubbing (VI)' },
	['item_140264']: { pagename: 'Guild Insignia Rubbing (VII)' },
	['item_140265']: { pagename: 'Guild Insignia Rubbing (VIII)' },
	['item_140266']: { pagename: '"A Departing Voyager"' },
	['item_140267']: { pagename: '"Heartbroken Lovers"' },
	['item_140268']: { pagename: '"Friends Going Separate Ways"' },
	['item_140271']: { pagename: 'Revelation Slate' },
	['item_140272']: { pagename: 'Todd\'s Notebook' },
	['item_140273']: { pagename: 'Fan With Plain Carp Print' },
	['item_140274']: { pagename: 'The Amicassador\'s Seal' },
	['item_140275']: { pagename: 'Small Chest Sent to the Sleepless Earl' },
	['item_140276']: { pagename: 'Kitchen Knife Sent to Spices Supreme' },
	['item_140277']: { pagename: 'An Archery Set Gifted For Someone Unknown' },
	['item_140278']: { pagename: 'New Tea "Tingyun\'s Blend"' },
	['item_140279']: { pagename: 'Chili Oil Beef Offal Stew' },
	['item_140280']: { pagename: 'Soul-Soothing Paper Kite' },
	['item_140281']: { pagename: 'Jade Abacus of Allying Oath' },
	['item_140282']: { pagename: 'Encryption Key Treasure Map' },
	['item_140283']: { pagename: 'Treasure Map No. 1' },
	['item_140284']: { pagename: 'Treasure Map No. 2' },
	['item_140285']: { pagename: 'Treasure Map No. 3' },
	['item_140286']: { pagename: 'Aether Coin' },
	['item_140287']: { pagename: 'Elevator Encryption Key' },
	['item_140288']: { pagename: 'Championship Contender Pass 1' },
	['item_140289']: { pagename: 'Championship Contender Pass 2' },
	['item_140290']: { pagename: 'Championship Contender Pass 3' },
	['item_140291']: { pagename: 'Icefire Lotus' },
	['item_140292']: { pagename: 'Life-Death Polypore' },
	['item_140293']: { pagename: 'Whirlbolt Pneumatophore' },
	['item_140294']: { pagename: 'Elixir of Dragon Oil' },
	['item_140295']: { pagename: 'Growth Booster' },
	['item_140296']: { pagename: 'Treasure Map Indicating the Location of Ignis Aureliae' },
	['item_140298']: { pagename: 'Hilt-Wood From the Arbor' },
	['item_140299']: { pagename: 'Ignis Aureliae' },
	// ['item_140300']: { pagename: 'Reaper of Nexus Modder (1)' },
	// ['item_140300']: { pagename: 'Star-Shattering Blade of Truth (1)' },
	['item_140300']: { pagename: 'Big Sword (1)' },
	['item_140301']: { pagename: 'Imaginary Intra-Kinetic Portable Tactical Laser Cannon (1)' },
	['item_140302']: { pagename: 'High Elders\' Secret Treasure' },
	['item_140303']: { pagename: 'Legend of the Trailblazer' },
	// ['item_140304']: { pagename: 'Star-Shattering Blade of Truth (2)' },
	['item_140304']: { pagename: 'Big Sword (2)' },
	// ['item_140304']: { pagename: 'Reaper of Nexus Modder (2)' },
	['item_140305']: { pagename: 'Imaginary Intra-Kinetic Portable Tactical Laser Cannon (2)' },
	['item_140306']: { pagename: 'Pan-Cosmic Quick Diagnosis Booklet' },
	['item_140307']: { pagename: 'Celestial Jade Game Record' },
	['item_140308']: { pagename: 'Copy of Medical Certificate' },
	['item_140309']: { pagename: 'Collaboration Invitation from the Interastral Peace Corporation' },
	['item_140311']: { pagename: 'March 7th\'s "Origin"' },
	['item_140312']: { pagename: 'Drops from Abominations of Abundance' },
	['item_140314']: { pagename: 'Authorized Recordings by Mr. Xiyan' },
	['item_140315']: { pagename: 'Authorized Recordings by Back\'n and Forth' },
	['item_140316']: { pagename: 'Mr. Huo\'s Confidential Merchandise' },
	['item_140320']: { pagename: 'Cognition Chasm: Confidence Crisis' },
	['item_140321']: { pagename: 'Cognition Chasm: Researchers\' Disappearance' },
	['item_140322']: { pagename: 'Cognition Chasm: The Xianzhou Alliance' },
	['item_140323']: { pagename: 'Cognition Chasm: Energy Lifeform' },
	['item_140324']: { pagename: 'Cognition Chasm: Spontaneous Human Combustion' },
	['item_140325']: { pagename: 'Cognition Chasm: Genius Society Member' },
	['item_140326']: { pagename: 'Clue: Missing Researcher List' },
	['item_140327']: { pagename: 'Clue: "Phrase"' },
	['item_140328']: { pagename: 'Clue: Booklet' },
	['item_140329']: { pagename: 'Clue: Dimension-Phasing Flame' },
	['item_140339']: { pagename: 'Case Review (I)' },
	['item_140340']: { pagename: 'Case Review (II)' },
	['item_140341']: { pagename: 'Evidence: Shamari\'s ID' },
	['item_140342']: { pagename: 'Evidence: Giant Wooden Hammer' },
	['item_140343']: { pagename: 'Evidence: Goldhammer Residence Security Regulations' },
	['item_140344']: { pagename: 'Evidence: "Mutual Assured Destruction" Button' },
	['item_140345']: { pagename: 'Evidence: Pom-Pom Toy' },
	['item_140346']: { pagename: 'Evidence: Qian Ketong\'s Account Book' },
	['item_140347']: { pagename: 'Evidence: Lefton\'s Tie' },
	['item_140348']: { pagename: 'Evidence: Wright\'s Stool' },
	['item_140349']: { pagename: 'Evidence: Zhongshan\'s Ring' },
	['item_140350']: { pagename: 'Evidence: Smoked Red Herring' },
	['item_140351']: { pagename: 'Proof of Trust' },
	['item_140352']: { pagename: 'Nameless\'s Memory Bubble' },
	['item_140355']: { pagename: 'Gift From a Fan' },
	['item_140356']: { pagename: 'Property Deed' },
	['item_140357']: { pagename: 'Gold Subscription Commemorative Medallion' },
	['item_140358']: { pagename: 'Silver Subscription Commemorative Medallion' },
	['item_140362']: { pagename: 'Harmonic Chime' },
	['item_140363']: { pagename: 'Fragmented Record of Belobog Ancient Martial Arts' },
	['item_140364']: { pagename: 'Guqin Recording' },
	['item_140365']: { pagename: 'New Guqin Recording' },
	['item_140366']: { pagename: 'Unusually Colored Lodestone' },
	['item_140372']: { pagename: 'Family Photo' },
	['item_140373']: { pagename: 'Discarded Letter Sheets' },
	['item_140374']: { pagename: 'Rubbings on Paper' },
	['item_140376']: { pagename: 'Square Rice Ball' },
	['item_140377']: { pagename: 'Shattered Cloud Knight Devastator Glaive' },
	['item_140378']: { pagename: 'Old Bell' },
	['item_140381']: { pagename: 'Unremarkable Trash' },
	['item_140382']: { pagename: 'One-of-a-Kind Trash' },
	['item_140388']: { pagename: 'Average Trash' },
	['item_140394']: { pagename: 'Numbers-got-Nerfed Trash' },
	['item_140395']: { pagename: 'Emotion Prototype: The Moment of Betrayal' },
	['item_140396']: { pagename: 'Emotion Prototype: The Cloud of Doubt' },
	['item_140397']: { pagename: 'Emotion Prototype: Everlasting Hatred' },
	['item_140398']: { pagename: 'Emotion Prototype: Broken Dreams' },
	['item_140399']: { pagename: 'Emotion Prototype: Momentary Freedom' },
	['item_140400']: { pagename: 'Unknown Puzzle Fragment' },
	['item_140401']: { pagename: 'Firefly\'s Budget' },
	['item_140402']: { pagename: 'Cosmic Fried Rice (Overnight Edition)' },
	['item_140403']: { pagename: 'Abnormal images from surveillance records' },
	['item_140404']: { pagename: 'External communication records' },
	['item_140405']: { pagename: 'Freshly-Baked Cake' },
	['item_140406']: { pagename: '"Calm" Gear' },
	['item_140407']: { pagename: '"Happy" Gear' },
	['item_140408']: { pagename: '"Sad" Gear' },
	['item_140409']: { pagename: '"Angry" Gear' },
	['item_140410']: { pagename: 'Lesley Dean\'s Rebirth Project' },
	['item_140412']: { pagename: 'Half-Autographed Photo' },
	['item_140414']: { pagename: 'Aventurine\'s Token' },
	['item_140415']: { pagename: 'Steinway Falcon Luxury Speedster (Black)' },
	['item_140416']: { pagename: 'Steinway Falcon Luxury Speedster (Rental)' },
	['item_140417']: { pagename: 'Steinway Falcon Luxury Speedster (Gold)' },
	['item_140418']: { pagename: 'Steinway Falcon Luxury Speedster (Blue)' },
	['item_140419']: { pagename: 'Utopon Unicycler' },
	['item_140421']: { pagename: 'Employees\' Idle Chatter' },
	['item_140422']: { pagename: 'TV News' },
	['item_140430']: { pagename: 'Golden Limited - Aideen Token' },
	['item_140431']: { pagename: 'Medicine of Unknown Use' },
	['item_140432']: { pagename: 'Eerie Building Block' },
	['item_140434']: { pagename: 'Ace Gambler\'s Precious Part' },
	['item_140436']: { pagename: 'Components From a Certain Ruin' },
	['item_140440']: { pagename: 'Fate\'s Epistle' },
	['item_140443']: { pagename: 'Pinball Machine Model' },
	['item_140449']: { pagename: 'Mundanite\'s Insight' },
	['item_140450']: { pagename: '"Mutually Assured Destruction" Button' },
	['item_140465']: { pagename: 'Commemorative Photo' },
	['item_140468']: { pagename: 'Indefinite Patent Operative Omnifier' },
	['item_140469']: { pagename: '"Happy" Gear (Gentleness, the Name of Nocturne)' },
	['item_140470']: { pagename: 'Oksana\'s "Toys"' },
	['item_149959']: { pagename: 'Thermic Core' },
	['item_149977']: { pagename: 'Portrait With a Clue' },
	['item_149978']: { pagename: 'Pela\'s Notes' },
	['item_149979']: { pagename: 'Edited Note' },
	['item_149983']: { pagename: 'Beacon Data' },
	['item_149991']: { pagename: 'Box of Metal Plates and Bandages' },
	['item_150010']: { pagename: 'Recipe: Dream Syrup' },
	['item_150011']: { pagename: 'Recipe: Classic SoulGlad (Mission Item)' },
	['item_150012']: { pagename: 'Recipe: Bright Future' },
	['item_150013']: { pagename: 'Recipe: High Stakes' },
	['item_150014']: { pagename: 'Recipe: Pika White Grape Soda' },
	['item_150015']: { pagename: 'Recipe: Eternal Endurance' },
	['item_180001']: { pagename: 'Solid Water' },
	['item_180002']: { pagename: 'Basic Ingredients' },
	['item_180004']: { pagename: 'Phlogiston' },
	['item_180005']: { pagename: 'Metal' },
	['item_180006']: { pagename: 'Gaseous Liquid' },
	['item_180007']: { pagename: 'Seed' },
	['item_180008']: { pagename: 'Discarded Ingenium Parts' },
	['item_180009']: { pagename: 'Human-Height Auspicious Crops' },
	['item_18001']: { pagename: 'Shadow of Destruction' },
	['item_180010']: { pagename: 'Tranquility' },
	['item_180011']: { pagename: 'Broken Dreams' },
	['item_180012']: { pagename: 'Rusty Gear' },
	['item_18003']: { pagename: 'Shadow of Preservation' },
	['item_181001']: { pagename: 'Mechanical Parts' },
	['item_181002']: { pagename: 'Virtual Particle' },
	['item_181003']: { pagename: 'Protein Rice' },
	['item_181004']: { pagename: 'Feather of Flame' },
	['item_181005']: { pagename: 'Core of Ice' },
	['item_181006']: { pagename: 'Eye of Lightning' },
	['item_181007']: { pagename: 'Vortex of Wind' },
	['item_181008']: { pagename: 'Quantum Ripples' },
	['item_181009']: { pagename: 'Leaf of Imaginary' },
	['item_181010']: { pagename: 'Meteoric Alloy' },
	['item_181011']: { pagename: 'Jade Abacus Unit' },
	['item_181012']: { pagename: 'Extract of Medicinal Herbs' },
	['item_181013']: { pagename: 'Tian Dong' },
	['item_181014']: { pagename: 'Confounding' },
	['item_181015']: { pagename: 'Hunger' },
	['item_181016']: { pagename: 'Old Molar' },
	['item_182001']: { pagename: 'Strange Matter of Destruction' },
	['item_182002']: { pagename: 'Ambergris of Abundance' },
	['item_182003']: { pagename: 'Stone of The Hunt' },
	['item_182004']: { pagename: 'Preservation Construction Material' },
	['item_182005']: { pagename: 'Hard Chip of Nihility' },
	['item_182006']: { pagename: 'Tree Bark of Erudition' },
	['item_182007']: { pagename: 'Slime of Harmony' },
	['item_182008']: { pagename: 'Dragon Scale Coral' },
	['item_182009']: { pagename: 'The Sound and the Fury (Item)' },
	['item_182010']: { pagename: 'Thermal Gel' },
	['item_183001']: { pagename: 'Interdimensional Leaf' },
	['item_183002']: { pagename: 'Phase Flame' },
	['item_183003']: { pagename: 'Tear Crystal of Glorious Death' },
	['item_183004']: { pagename: 'Mythus Knots' },
	['item_183005']: { pagename: 'Weary' },
	['item_183006']: { pagename: 'Mechanical Cube' },
	['item_2']: { pagename: 'Credit' },
	['item_200101']: { pagename: 'March 7th - Welcome (Profile Picture)' },
	['item_200102']: { pagename: 'Dan Heng - Welcome (Profile Picture)' },
	['item_200103']: { pagename: 'Himeko - Welcome (Profile Picture)' },
	['item_200104']: { pagename: 'Welt - Welcome (Profile Picture)' },
	['item_200105;200106']: { pagename: 'Trailblazer — Welcome (Profile Picture)' },
	['item_200107']: { pagename: 'Kafka: Dinner Party (Profile Picture)' },
	['item_200108']: { pagename: 'Blade: Dinner Party (Profile Picture)' },
	['item_200109']: { pagename: 'Jing Yuan: In Leisure (Profile Picture)' },
	['item_200110']: { pagename: 'Fu Xuan: In Leisure (Profile Picture)' },
	['item_200111']: { pagename: 'Bronya: Celebration (Profile Picture)' },
	['item_200112']: { pagename: 'Gepard: Celebration (Profile Picture)' },
	['item_200113']: { pagename: 'Jingliu: Odyssey (Profile Picture)' },
	['item_200114']: { pagename: 'Yanqing: Odyssey (Profile Picture)' },
	['item_200115']: { pagename: 'Ruan Mei: Academia (Profile Picture)' },
	['item_200116']: { pagename: 'Dr. Ratio: Academia (Profile Picture)' },
	['item_200117']: { pagename: 'Sparkle: Illusion (Profile Picture)' },
	['item_200118']: { pagename: 'Sampo: Illusion (Profile Picture)' },
	['item_200119']: { pagename: 'Topaz: Bullseye (Profile Picture)' },
	['item_200120']: { pagename: 'Aventurine: Bullseye (Profile Picture)' },
	['item_201']: { pagename: 'Fuel' },
	['item_202003']: { pagename: 'Junjun (Profile Picture)' },
	['item_202005']: { pagename: 'Diting (Profile Picture)' },
	['item_202008']: { pagename: 'Snack Life (Profile Picture)' },
	['item_202009;202010']: { pagename: 'Trailblazer: Star Rail (Profile Picture)' },
	['item_202011']: { pagename: 'Clockie (Profile Picture)' },
	['item_202012']: { pagename: 'Brother Hanu (Profile Picture)' },
	['item_202013']: { pagename: 'Origami Bird (Profile Picture)' },
	['item_202014']: { pagename: 'Kakavasha (Profile Picture)' },
	['item_202015']: { pagename: 'Hamster Ball Knight (Profile Picture)' },
	['item_202016']: { pagename: 'One-Year Anniversary Commemoration (Profile Picture)' },
	['item_210001']: { pagename: '"Dawn of Disaster"' },
	['item_210003']: { pagename: '"fReeStyLE"' },
	['item_210008']: { pagename: '"Crises"' },
	['item_210010']: { pagename: '"Flashpoint"' },
	['item_210100']: { pagename: '"Order"' },
	['item_210101']: { pagename: '"Kindling"' },
	['item_210102']: { pagename: '"Underground"' },
	['item_210103']: { pagename: '"Godfather"' },
	['item_210104']: { pagename: '"Frozen March"' },
	['item_210105']: { pagename: '"A Trap With No Return"' },
	['item_210106']: { pagename: '"Wildfire"' },
	['item_210108']: { pagename: '"Ghost From the Past"' },
	['item_210109']: { pagename: '"Everwinter"' },
	['item_210110']: { pagename: '"Fate"' },
	['item_210111']: { pagename: '"Embers"' },
	['item_210112']: { pagename: '"Hearthfire"' },
	['item_210113']: { pagename: '"Warm Sun"' },
	['item_210114']: { pagename: '"Streets Abuzz"' },
	['item_210115']: { pagename: '"Sleep Tight"' },
	['item_210200']: { pagename: '"Cumulus Formations"' },
	['item_210201']: { pagename: '"Ave Astra et Viator"' },
	['item_210202']: { pagename: '"Upon the Firmament"' },
	['item_210203']: { pagename: '"Exquisite Ingenuity"' },
	['item_210204']: { pagename: '"Anthropic Domain"' },
	['item_210205']: { pagename: '"Warden of Jade"' },
	['item_210206']: { pagename: '"Into the Desolate"' },
	['item_210207']: { pagename: '"Blade Abracadabra"' },
	['item_210208']: { pagename: '"Deerstalker"' },
	['item_210209']: { pagename: '"Lustrous Moonlight"' },
	['item_210210']: { pagename: '"Fabulous Foresight"' },
	['item_210211']: { pagename: '"Thundering Chariot"' },
	['item_210212']: { pagename: '"Hunter\'s Intuition"' },
	['item_210213']: { pagename: '"Into the Breach"' },
	['item_210214']: { pagename: '"Sanctus Medicus Dharani"' },
	['item_210215']: { pagename: '"Mokshasatya"' },
	['item_210216']: { pagename: '"Gleaming Clash"' },
	['item_210217']: { pagename: '"Evanescent Dreams"' },
	['item_210218']: { pagename: '"Erstwhile Resonance"' },
	['item_210219']: { pagename: '"Samudrartha"' },
	['item_210220']: { pagename: '"Obscured Pearls"' },
	['item_210221']: { pagename: '"Arteria Inceptionis"' },
	['item_210222']: { pagename: '"Pedujara: Ephemeral Cycle"' },
	['item_210223']: { pagename: '"Pedujara: Even Immortality Ends"' },
	['item_210224']: { pagename: '"Pedujara: Demiseless Existence"' },
	['item_210225']: { pagename: '"Paean of Indulgence"' },
	['item_210226']: { pagename: '"Cosmic Sacrifice for Love"' },
	['item_210227']: { pagename: '"A Gentleman\'s Fantasy"' },
	['item_210228']: { pagename: '"Dancing Fantasms"' },
	['item_210229']: { pagename: '"Nesting Avians"' },
	['item_210300']: { pagename: '"Against The Day"' },
	['item_210301']: { pagename: '"Challenge to the Reader"' },
	['item_210302']: { pagename: '"The Player on The Other Side"' },
	['item_210303']: { pagename: '"Fair Play"' },
	['item_210304']: { pagename: '"Return of None"' },
	['item_210305']: { pagename: '"Nevermore"' },
	['item_210306']: { pagename: '"This Side of Paradise"' },
	['item_210307']: { pagename: '"Golden Land"' },
	['item_210308']: { pagename: '"Ace in the Hole"' },
	['item_210309']: { pagename: '"The Big Sleep"' },
	['item_210310']: { pagename: '"Realitätsprinzip"' },
	['item_210311']: { pagename: '"Lustprinzip"' },
	['item_210312']: { pagename: '"Halfway House"' },
	['item_210313']: { pagename: '"If I Can Stop One Heart From Breaking"' },
	['item_210314']: { pagename: '"Chaîne Signifiante"' },
	['item_210315']: { pagename: '"Stade du Miroir"' },
	['item_210316']: { pagename: 'City Upon a Hill (Disk)' },
	['item_210317']: { pagename: 'Spellbound (Disk)' },
	['item_210318']: { pagename: 'Hi, Dolly! (Disk)' },
	['item_210319']: { pagename: 'The Midnight Special (Disk)' },
	['item_210320']: { pagename: 'If One Wakes at Midnight (Disk)' },
	['item_210321']: { pagename: 'Stranger Than Paradise (Disk)' },
	['item_210322']: { pagename: 'On The Disintegration of Evermemoria (Disk)' },
	['item_210323']: { pagename: 'Citizen Hanunue (Disk)' },
	['item_212']: { pagename: 'Adventure Log' },
	['item_213']: { pagename: 'Traveler\'s Guide' },
	['item_22']: { pagename: 'Trailblaze EXP' },
	['item_220000']: { pagename: 'The Art of Language' },
	['item_220001']: { pagename: 'Where\'s the Rabbit?' },
	['item_220002']: { pagename: 'Warp Trotter (Chat Box)' },
	['item_220003']: { pagename: 'Celestial Incubator' },
	['item_220004']: { pagename: 'Monster Tavern' },
	['item_221']: { pagename: 'Sparse Aether' },
	['item_221000']: { pagename: 'Nameless Journey' },
	['item_221001']: { pagename: 'Ingenium Dreams' },
	['item_221003']: { pagename: 'Starfire Parkland' },
	['item_221004']: { pagename: 'The Planet of Festivities' },
	['item_221005']: { pagename: 'Cosmodyssey (Phone Wallpaper)' },
	['item_222']: { pagename: 'Condensed Aether' },
	['item_222000']: { pagename: 'Dreamscape Pass (Mission Item)' },
	['item_223']: { pagename: 'Refined Aether' },
	['item_223000']: { pagename: 'Aventurine (Dreamscape Pass Sticker)' },
	['item_223001']: { pagename: 'Black Swan (Dreamscape Pass Sticker)' },
	['item_223002']: { pagename: 'Sparkle (Dreamscape Pass Sticker)' },
	['item_223003']: { pagename: 'Acheron (Dreamscape Pass Sticker)' },
	['item_223004']: { pagename: 'Firefly (Dreamscape Pass Sticker)' },
	['item_223005']: { pagename: 'Misha (Dreamscape Pass Sticker)' },
	['item_223006']: { pagename: 'Robin (The Reverie Sticker)' },
	['item_223007']: { pagename: 'Stellaron Hunter: Sam (Dreamscape Pass Sticker)' },
	['item_223008']: { pagename: 'Sunday (Dreamscape Pass Sticker)' },
	['item_223009']: { pagename: 'Gallagher (Dreamscape Pass Sticker)' },
	['item_223010']: { pagename: 'Dr. Ratio (Dreamscape Pass Sticker)' },
	['item_223020']: { pagename: 'About Money' },
	['item_223021']: { pagename: 'About Happiness' },
	['item_223022']: { pagename: 'About Love' },
	['item_223023']: { pagename: 'About Life' },
	['item_223024']: { pagename: 'About Death' },
	['item_223050']: { pagename: 'The Family (Dreamscape Pass Sticker)' },
	['item_223051']: { pagename: 'Celebrity' },
	['item_223052']: { pagename: 'Merchant (Dreamscape Pass Sticker)' },
	['item_223053']: { pagename: 'Tyrant' },
	['item_223054']: { pagename: 'Scholar' },
	['item_223055']: { pagename: 'Messenger (Dreamscape Pass Sticker)' },
	['item_223056']: { pagename: 'Hero' },
	['item_223058']: { pagename: 'The Reverie VIP Lounge' },
	['item_223059']: { pagename: 'Daughter' },
	['item_223080']: { pagename: 'Who is this?' },
	['item_223081']: { pagename: 'Distance' },
	['item_223082']: { pagename: 'Great People' },
	['item_223083']: { pagename: 'Best Buddies' },
	['item_223084']: { pagename: 'True Grit' },
	['item_223085']: { pagename: 'Blank Tile' },
	['item_223100']: { pagename: 'Oti Mall (Dreamscape Pass Sticker)' },
	['item_223101']: { pagename: 'Dreamscape Sales Store (Dreamscape Pass Sticker)' },
	['item_223102']: { pagename: 'Golden Central Station' },
	['item_223103']: { pagename: '"Sales Rep"' },
	['item_223104']: { pagename: 'Cash-Spewer (Dreamscape Pass Sticker)' },
	['item_223105']: { pagename: 'Classic SoulGlad (Dreamscape Pass Sticker)' },
	['item_223106']: { pagename: 'Golden Times' },
	['item_223107']: { pagename: 'Floatdisc Burger (Dreamscape Pass Sticker)' },
	['item_223108']: { pagename: 'Nameless\' Dream Bubble' },
	['item_223152']: { pagename: 'Eye of Dreamchaser' },
	['item_223153']: { pagename: 'Penacony TV Station' },
	['item_223154']: { pagename: 'The Family Needs You!' },
	['item_223155']: { pagename: 'Empyrean Hymnos' },
	['item_223156']: { pagename: 'Smokescreen' },
	['item_223157']: { pagename: 'Sound of Chaos' },
	['item_223180']: { pagename: 'Clipping (I)' },
	['item_223181']: { pagename: 'Clipping (II)' },
	['item_223182']: { pagename: 'Clipping (III)' },
	['item_223183']: { pagename: 'Clipping (IV)' },
	['item_223184']: { pagename: 'Clipping (V)' },
	['item_223185']: { pagename: 'Clipping (VI)' },
	['item_223200']: { pagename: 'Aideen Park (Dreamscape Pass Sticker)' },
	['item_223201']: { pagename: 'Golden Capsule Machine (Dreamscape Pass Sticker)' },
	['item_223202']: { pagename: 'Let\'s Dance' },
	['item_223203']: { pagename: 'Clock Credits (Dreamscape Pass Sticker)' },
	['item_223204']: { pagename: 'Aideen Tokens (Dreamscape Pass Sticker)' },
	['item_223205']: { pagename: 'Yes, It\'s All Yours' },
	['item_223206']: { pagename: 'Good-Omen Capsule Machine' },
	['item_223207']: { pagename: 'Cosmos\' Most Lucky Capsule Machine' },
	['item_223208']: { pagename: 'Enjoy Your Drink' },
	['item_223230']: { pagename: 'Anecdote (I)' },
	['item_223231']: { pagename: 'Anecdote (II)' },
	['item_223232']: { pagename: 'Anecdote (III)' },
	['item_223233']: { pagename: 'Anecdote (IV)' },
	['item_223250']: { pagename: 'Hey! I\'m Clockie' },
	['item_223252']: { pagename: 'Sadie' },
	['item_223253']: { pagename: 'Angrie' },
	['item_223254']: { pagename: 'Happie' },
	['item_223255']: { pagename: 'Calmie' },
	['item_223256']: { pagename: 'Look! He\'s Called Brother Hanu' },
	['item_223258']: { pagename: 'Hey! Isn\'t This The Origami Bird?' },
	['item_223259']: { pagename: 'Flying With Your Dream In Your Mouth' },
	['item_223260']: { pagename: 'Ah! The Annoying Boss Stone!' },
	['item_223261']: { pagename: 'A Pure Antagonist' },
	['item_223270']: { pagename: 'Line: Violence' },
	['item_223271']: { pagename: 'Line: Affection' },
	['item_223272']: { pagename: 'Line: Philosophy' },
	['item_223273']: { pagename: 'Line: Narcissism' },
	['item_223274']: { pagename: 'Line: Inferiority' },
	['item_223300']: { pagename: 'The Family\'s Construction Authority (Dreamscape Pass Sticker)' },
	['item_223301']: { pagename: 'Observation Deck' },
	['item_223302']: { pagename: 'A Strange Statue' },
	['item_223303']: { pagename: 'Producer' },
	['item_223304']: { pagename: 'Pirate' },
	['item_223305']: { pagename: 'Action (Dreamscape Pass Sticker)' },
	['item_223306']: { pagename: 'Dreambird' },
	['item_223307']: { pagename: 'Dreambird (Another one)' },
	['item_223308']: { pagename: 'Mr. Stone' },
	['item_223309']: { pagename: 'Soda Bottle' },
	['item_223330']: { pagename: 'Dreamweaver: Angry' },
	['item_223331']: { pagename: 'Dreamweaver: Pursuit' },
	['item_223332']: { pagename: 'Dreamweaver: Obsession' },
	['item_223333']: { pagename: 'Dreamweaver: Fatigue' },
	['item_223334']: { pagename: 'Dreamweaver: Resignation' },
	['item_223350']: { pagename: 'Icy Fountain of Memory' },
	['item_223351']: { pagename: 'Toy House' },
	['item_223352']: { pagename: 'Study' },
	['item_223353']: { pagename: 'Grandpa\'s Work' },
	['item_223354']: { pagename: 'Migratory Memory' },
	['item_223355']: { pagename: 'Frozen Memory' },
	['item_223356']: { pagename: 'Chair' },
	['item_223357']: { pagename: 'Building Blocks' },
	['item_223358']: { pagename: 'Balloon (Dreamscape Pass Sticker)' },
	['item_223370']: { pagename: 'Memories (I)' },
	['item_223371']: { pagename: 'Memories (II)' },
	['item_223372']: { pagename: 'Memories (III)' },
	['item_223373']: { pagename: 'Memories (IV)' },
	['item_223400']: { pagename: 'Dreamscape Room' },
	['item_223401']: { pagename: 'Dreamscape Lobby (Dreamscape Pass Sticker)' },
	['item_223402']: { pagename: 'Monitoring Room (Dreamscape Pass Sticker)' },
	['item_223403']: { pagename: 'Allseer (Dreamscape Pass Sticker)' },
	['item_223404']: { pagename: 'Heartbreaker (Dreamscape Pass Sticker)' },
	['item_223405']: { pagename: 'Something Unto Death (Dreamscape Pass Sticker)' },
	['item_223406']: { pagename: 'W?' },
	['item_223408']: { pagename: 'No Signal' },
	['item_223409']: { pagename: 'Faulty Screen' },
	['item_223430']: { pagename: 'Lost (I)' },
	['item_223431']: { pagename: 'Lost (II)' },
	['item_223432']: { pagename: 'Lost (III)' },
	['item_223433']: { pagename: 'Lost (IV)' },
	['item_223434']: { pagename: 'Lost (V)' },
	['item_223500']: { pagename: 'Theme Park Guide' },
	['item_223501']: { pagename: 'Best Buddies (I)' },
	['item_223502']: { pagename: 'Best Buddies (II)' },
	['item_223503']: { pagename: 'Gaseous Laughter' },
	['item_223504']: { pagename: '3... 2... 1... Action!' },
	['item_223505']: { pagename: 'No Open Flames Allowed' },
	['item_223506']: { pagename: '"Philanthropist"' },
	['item_223507']: { pagename: 'Penacony City Mob' },
	['item_223508']: { pagename: 'Hamster Speedrun' },
	['item_223509']: { pagename: 'Limousine Cinema' },
	['item_223531']: { pagename: 'Clockie\'s Quote' },
	['item_223532']: { pagename: 'Brother Hanu\'s Quote' },
	['item_223533']: { pagename: 'Hamster Ball Knight\'s Quote' },
	['item_223534']: { pagename: 'Boss Stone\'s Quote' },
	['item_223600']: { pagename: 'City Sandpit: Entrance' },
	['item_223601']: { pagename: 'City Sandpit: Foundation' },
	['item_223602']: { pagename: 'City Sandpit: Building Complex' },
	['item_223603']: { pagename: 'City Sandpit: Advertisement' },
	['item_223604']: { pagename: 'City Sandpit: SoulGlad' },
	['item_223605']: { pagename: 'City Sandpit: Booth' },
	['item_223606']: { pagename: 'City Sandpit: Force of Evil' },
	['item_223607']: { pagename: 'City Sandpit: Drunk "Little" Bird' },
	['item_223631']: { pagename: 'Conclusion of the 3rd Round of Inspection: Failed' },
	['item_223632']: { pagename: 'Conclusion of the 8th Round of Inspection: Failed' },
	['item_223633']: { pagename: 'Conclusion of the 11th Round of Inspection: Failed' },
	['item_223634']: { pagename: 'Conclusion of the 20th Round of Inspection: Failed' },
	['item_223700']: { pagename: 'Oak (Dreamscape Pass Sticker)' },
	['item_223701']: { pagename: 'Alfalfa (Dreamscape Pass Sticker)' },
	['item_223702']: { pagename: 'Nightingale (Dreamscape Pass Sticker)' },
	['item_223703']: { pagename: 'Bloodhound (Dreamscape Pass Sticker)' },
	['item_223704']: { pagename: 'Iris (Dreamscape Pass Sticker)' },
	['item_223705']: { pagename: 'Mr. Aideen (Dreamscape Pass Sticker)' },
	['item_223706']: { pagename: 'Oti Alfalfa (Dreamscape Pass Sticker)' },
	['item_223708']: { pagename: 'Hamz (Dreamscape Pass Sticker)' },
	['item_223710']: { pagename: 'Lesley Dean (Dreamscape Pass Sticker)' },
	['item_223712']: { pagename: 'Robin (Stars in the Dream Sticker)' },
	['item_223713']: { pagename: 'Maeven Ellis (Dreamscape Pass Sticker)' },
	['item_223714']: { pagename: 'Gopher Wood (Dreamscape Pass Sticker)' },
	['item_223731']: { pagename: 'Oak Family Teachings' },
	['item_223732']: { pagename: 'Alfalfa Family Teachings' },
	['item_223733']: { pagename: 'Nightingale Family Teachings' },
	['item_223734']: { pagename: 'Bloodhound Family Teachings' },
	['item_223735']: { pagename: 'Iris Family Teachings' },
	['item_232']: { pagename: 'Lost Gold Fragment' },
	['item_233']: { pagename: 'Lost Crystal' },
	['item_241']: { pagename: 'Tracks of Destiny' },
	['item_250201']: { pagename: 'Malfunctioning Chip' },
	['item_250202']: { pagename: 'Defective Suppression Chip' },
	['item_250203']: { pagename: 'Emergency Reboot Chip' },
	['item_250204']: { pagename: 'Trotter Patch Chip' },
	['item_250205']: { pagename: 'Morale Activation Chip' },
	['item_250207']: { pagename: 'Performance Allocation Chip' },
	['item_250208']: { pagename: 'Efficiency Optimization Chip' },
	['item_250209']: { pagename: 'High Load-Low Speed Chip' },
	['item_250210']: { pagename: 'Sudden Evasion Chip' },
	['item_250211']: { pagename: 'Safe Mode Chip' },
	['item_250212']: { pagename: 'Threshold Disruption Chip' },
	['item_250213']: { pagename: 'Freeze Loophole Chip' },
	['item_250214']: { pagename: 'Shield System Chip' },
	['item_250215']: { pagename: 'Backstage Enhancement Chip' },
	['item_250216']: { pagename: 'Sudden Interjection Chip' },
	['item_250217']: { pagename: 'Wind Shear Loophole Chip' },
	['item_250218']: { pagename: 'Matrix Iteration Chip' },
	['item_250219']: { pagename: 'Attack Interception Chip' },
	['item_250220']: { pagename: 'Auto-Repair Chip' },
	['item_250221']: { pagename: 'Data Retrieval Chip' },
	['item_250222']: { pagename: 'Parallel Enhancement Chip' },
	['item_250223']: { pagename: 'Saturated Activation Chip' },
	['item_250224']: { pagename: 'Quick Command Chip' },
	['item_250225']: { pagename: 'Shieldbreaker Chip' },
	['item_250226']: { pagename: 'Functional Overdraft Chip' },
	['item_250227']: { pagename: 'Energy Recycling Chip' },
	['item_250228']: { pagename: 'Computation Lock Chip' },
	['item_250229']: { pagename: 'Cleansing Chip' },
	['item_250230']: { pagename: 'Firewall Chip' },
	['item_250231']: { pagename: 'Negative Load Algorithm Chip' },
	['item_250232']: { pagename: 'Deep Clean Chip' },
	['item_250233']: { pagename: 'General Upgrade Chip' },
	['item_250320']: { pagename: 'Aether Spirit Upgrade Data' },
	['item_250401']: { pagename: 'Corridor of Fading Echoes Mastery Mark' },
	['item_250402']: { pagename: 'Cloudford Mastery Mark' },
	['item_250403']: { pagename: 'Herta Space Station Mastery Mark' },
	['item_250404']: { pagename: 'Great Mine Mastery Mark' },
	['item_262']: { pagename: 'Jade Feather' },
	['item_270000']: { pagename: 'Always Smiling' },
	['item_270001']: { pagename: 'Prosperity Certificate' },
	['item_270002']: { pagename: 'Gratuity Points' },
	['item_281001']: { pagename: 'Merchant Guild\'s Funds' },
	['item_281013']: { pagename: 'Neural Impulse' },
	['item_281014']: { pagename: 'Ordinary Dice' },
	['item_281015']: { pagename: 'Trailblaze Funds' },
	['item_281016']: { pagename: 'Remote Dice' },
	['item_281017']: { pagename: 'Reroll Coin' },
	['item_3']: { pagename: 'Oneiric Shard' },
	['item_300002']: { pagename: 'Gift of the Pathstriders' },
	['item_300003']: { pagename: 'Grand Gift of the Pathstriders' },
	['item_300004']: { pagename: 'Treasure of the Starry Seas' },
	['item_300020']: { pagename: 'Memo-Keeping Light Casket' },
	['item_300021']: { pagename: 'Sparkle\'s Wondrous Pack' },
	['item_300041']: { pagename: 'Supplies Material Box (Standard)' },
	['item_300052']: { pagename: 'Unclaimed Valuable Parcel' },
	['item_300101']: { pagename: 'Express Supply Pass' },
	['item_309002']: { pagename: 'Fateful Crossings: Hanu\'s Prison Break' },
	['item_309003']: { pagename: 'Fateful Crossings: Vignettes in a Cup' },
	['item_31']: { pagename: 'Cosmic Fragment' },
	['item_310001']: { pagename: 'Herta Contract: Trailblaze Aid' },
	['item_310002']: { pagename: 'Herta Contract: Fuel Refill' },
	['item_310003']: { pagename: 'Herta Contract: Quest Sharing' },
	['item_310005']: { pagename: 'Herta Contract: Aether Refill' },
	['item_310004']: { pagename: 'Herta Contract: Roaming Share' },
	['item_310006']: { pagename: 'Herta Contract: Resource Supply' },
	['item_310010']: { pagename: 'Herta Contract: Resource Supply V2' },
	['item_32']: { pagename: 'Ability Point' },
	['item_33']: { pagename: 'Immersifier' },
	['item_400004']: { pagename: 'Comfort Food' },
	['item_400005']: { pagename: 'Punitive Food' },
	['item_400006']: { pagename: 'Trick Snack' },
	['item_400007']: { pagename: 'Simple First-Aid Device' },
	['item_400008']: { pagename: 'Startaro Bubble' },
	['item_401003']: { pagename: 'Cosmic Fried Rice' },
	['item_401004']: { pagename: 'Yucky Fried Rice' },
	['item_401005']: { pagename: 'Punitive Energy' },
	['item_401006']: { pagename: 'Energy Drink' },
	['item_401007']: { pagename: 'Life Transmitter' },
	['item_401008']: { pagename: 'Bottled Soda' },
	['item_401009']: { pagename: 'Simple Protective Gear' },
	['item_401010']: { pagename: 'Rice Plant Panicle' },
	['item_401011']: { pagename: 'Camo Paint' },
	['item_401012']: { pagename: 'Diet Fried Rice' },
	['item_401013']: { pagename: 'Wrathful Gauntlets' },
	['item_401014']: { pagename: 'Fruitwood-Grilled Shantak Moa Drumettes' },
	['item_401016']: { pagename: 'Backscratcher' },
	['item_401020']: { pagename: 'Delicious Bean Cake' },
	['item_401021']: { pagename: 'Clockie Pizza (Single Slice)' },
	['item_401026']: { pagename: '"Sour Dreams" Soft Candy' },
	['item_401022']: { pagename: 'Sliced Cake Stargazer' },
	['item_401023']: { pagename: 'Mr. Herring\'s Lemon Tart' },
	['item_401024']: { pagename: 'Hundred-Layer Sundae (Zero Calories)' },
	['item_401025']: { pagename: 'Classic SoulGlad' },
	['item_401027']: { pagename: '"Dreamlight" Mixed Sweets' },
	['item_402001']: { pagename: 'Healing Spray' },
	['item_402002']: { pagename: 'Disposable Shield' },
	['item_402003']: { pagename: 'Energy Drink (sugar-free)' },
	['item_402004']: { pagename: 'Antimatter Field Generator' },
	['item_402005']: { pagename: 'High-Tech Protective Gear' },
	['item_402006']: { pagename: 'Inferior Protective Gear' },
	['item_402007']: { pagename: 'Tasty Field Nutrient Bar' },
	['item_402008']: { pagename: 'Dust of Alacrity' },
	['item_402009']: { pagename: 'Enhancement Paste: Physical' },
	['item_402010']: { pagename: 'Enhancement Paste: Wind' },
	['item_402012']: { pagename: 'Enhancement Paste: Ice' },
	['item_402011']: { pagename: 'Enhancement Paste: Fire' },
	['item_402014']: { pagename: 'Enhancement Paste: Quantum' },
	['item_402013']: { pagename: 'Enhancement Paste: Lightning' },
	['item_402015']: { pagename: 'Enhancement Paste: Imaginary' },
	['item_402016']: { pagename: 'Vomit Inducing Agent' },
	['item_402017']: { pagename: 'All Good Potion' },
	['item_402019']: { pagename: 'Prayer Machine' },
	['item_402020']: { pagename: 'Five-Grain Jade Elixir' },
	['item_402021']: { pagename: 'Health Detox Pill' },
	['item_402022']: { pagename: 'Jade Marrow Diffusion' },
	['item_402023']: { pagename: 'Pom-Pom\'s Fried Fowl' },
	['item_402025']: { pagename: 'Alfalfa Salad' },
	['item_402027']: { pagename: 'Fleeting Happiness' },
	['item_402028']: { pagename: 'The Cloud of Doubt' },
	['item_403001']: { pagename: 'Disposable Kinetic Arm' },
	['item_403002']: { pagename: 'Ruby Potion' },
	['item_403003']: { pagename: 'Disposable Kinetic Cannon' },
	['item_403004']: { pagename: 'Stone From the Everwinter Monument' },
	['item_403005']: { pagename: 'Topological Acceleration Band' },
	['item_403006']: { pagename: 'Longevity Pill of Cruelty' },
	['item_403007']: { pagename: 'Sugarball-Fried Viscorpi' },
	['item_403008']: { pagename: 'Automatic Wooden Dummy' },
	['item_403009']: { pagename: 'The Moment Before Death' },
	['item_403010']: { pagename: 'Bustling Ambience' },
	['item_405015']: { pagename: 'Flaming Potent Tea' },
	['item_408001']: { pagename: 'Trash' },
	['item_408002']: { pagename: 'Pleasant-Looking Trash' },
	['item_408003']: { pagename: 'Sanctity of the Trashcan' },
	['item_408004']: { pagename: 'Jim Roger Bread Soda' },
	['item_408005']: { pagename: 'Kapo-Kali' },
	['item_408201']: { pagename: 'Tuskpir Wrap' },
	['item_408202']: { pagename: 'Berrypheasant Skewers' },
	['item_408203']: { pagename: 'Rye Bread Soda Iceberg' },
	['item_408204']: { pagename: 'Stone-Roasted Meat Skewer' },
	['item_408205']: { pagename: 'Fighter Jet Lucky Plaque' },
	['item_408206']: { pagename: 'Grande Rejuvepill' },
	['item_408207']: { pagename: 'Short Rejuvepill' },
	['item_408208']: { pagename: 'Newspaper' },
	['item_408401']: { pagename: 'Snapper Jam Appetizer' },
	['item_408402']: { pagename: 'Crystal Lizard Satay' },
	['item_408403']: { pagename: 'Wild Herb Soup' },
	['item_408404']: { pagename: 'Deep-Fried Rock Crab' },
	['item_408405']: { pagename: 'Mung Bean Soda' },
	['item_408406']: { pagename: 'Scalegorge Spring Water' },
	['item_408407']: { pagename: 'Songlotus Cake' },
	['item_408408']: { pagename: 'Steamed Puffergoat Milk' },
	['item_408410']: { pagename: 'Sweet Dreams Soda' },
	['item_408411']: { pagename: 'Mineshroom' },
	['item_408412']: { pagename: 'Dry Emergency Light' },
	['item_408415']: { pagename: 'Popcorn' },
	['item_408416']: { pagename: 'Thundering Appetites' },
	['item_408417']: { pagename: 'Bright Future' },
	['item_408418']: { pagename: 'Dream Syrup' },
	['item_408601']: { pagename: 'Belobog Sausage' },
	['item_408602']: { pagename: 'Stone-Grilled Olm' },
	['item_408603']: { pagename: 'Immortal\'s Delight' },
	['item_408604']: { pagename: 'Rejuvenation Pellet' },
	['item_408605']: { pagename: 'Signature Chili Oil Beef Offal Stew' },
	['item_408607']: { pagename: 'Hypnotic Hammer' },
	['item_408608']: { pagename: 'Izumo Miso' },
	['item_408609']: { pagename: 'Floatdisc Burger' },
	['item_408610']: { pagename: 'Clockie Pizza (Whole)' },
	['item_408611']: { pagename: 'Potato Fries Sundae' },
	['item_408612']: { pagename: 'Oak Cake Rolls' },
	['item_408613']: { pagename: 'Pika White Grape Soda' },
	['item_408614']: { pagename: 'Murderer\'s Gaze' },
	['item_408615']: { pagename: 'Everlasting Hatred' },
	['item_408616']: { pagename: 'Eternal Endurance' },
	['item_408617']: { pagename: 'Duelist\'s Plume' },
	['item_408618']: { pagename: 'Gown of Extermination' },
	['item_408620']: { pagename: 'Dreamville Special' },
	['item_408621']: { pagename: 'Sweet Dreams Holographic Ticket' },
	['item_408622']: { pagename: 'Odd Gummy Candy' },
	['item_408623']: { pagename: 'Origami Family Bucket' },
	['item_408801']: { pagename: 'Dreamy Cone (Three Flavors)' },
	['item_53']: { pagename: 'Development Fund' },
	['item_60% New Thermal Mining Pickaxe']: { pagename: '60% New Thermal Mining Pickaxe' },
	['item_80% New Thermal Mining Pickaxe']: { pagename: '80% New Thermal Mining Pickaxe' },
	['item_Access Code for the "Chest"']: { pagename: 'Access Code for the "Chest"' },
	['item_All or Nothing']: { pagename: 'All or Nothing' },
	['item_Amber Huadiao Wine']: { pagename: 'Amber Huadiao Wine' },
	['item_Ball Peony']: { pagename: 'Ball Peony' },
	['item_Bizarre Tape']: { pagename: 'Bizarre Tape' },
	['item_Brumedew Concentrate Pellet']: { pagename: 'Brumedew Concentrate Pellet' },
	['item_Chef Pom-Pom']: { pagename: 'Chef Pom-Pom (Profile Picture)' },
	['item_Children\'s Fragrant Orange Pills']: { pagename: 'Children\'s Fragrant Orange Pills' },
	['item_Clothes for "That Teacher"']: { pagename: 'Clothes for "That Teacher"' },
	['item_Cloudbreadth Sleeves Limited Vertical Collar Jacket']: { pagename: 'Cloudbreadth Sleeves Limited Vertical Collar Jacket' },
	['item_Conductor\'s Treat']: { pagename: 'Conductor\'s Treat' },
	['item_Courtyard Gate Key']: { pagename: 'Courtyard Gate Key' },
	['item_Credbits']: { pagename: 'Credbits' },
	['item_Dark Fist Tournament Invitation Letter']: { pagename: 'Dark Fist Tournament Invitation Letter' },
	['item_Dazzling Golden Watch']: { pagename: 'Dazzling Golden Watch' },
	['item_Dazzling Rainbowite']: { pagename: 'Dazzling Rainbowite' },
	['item_Deep-fried Flying Sea Anemone']: { pagename: 'Deep-fried Flying Sea Anemone' },
	['item_Delicate Snow Globe']: { pagename: 'Delicate Snow Globe' },
	['item_Delicious Shumai']: { pagename: 'Delicious Shumai' },
	['item_Device Encryption Key']: { pagename: 'Device Encryption Key' },
	['item_Dirty Ribbon Tied to a Bell']: { pagename: 'Dirty Ribbon Tied to a Bell' },
	['item_Drifting Clouds']: { pagename: 'Drifting Clouds' },
	['item_Dud Grenade']: { pagename: 'Dud Grenade' },
	['item_Eerie Twig']: { pagename: 'Eerie Twig' },
	['item_Envision a Rose Forthcoming']: { pagename: 'Envision a Rose Forthcoming (Item)' },
	['item_Fateful Crossings: Aetherium Wars']: { pagename: 'Fateful Crossings: Aetherium Wars' },
	['item_First Snow']: { pagename: 'First Snow' },
	['item_Flower Made From Scrap Iron']: { pagename: 'Flower Made From Scrap Iron' },
	['item_Fragmentum Monster Armor']: { pagename: 'Fragmentum Monster Armor' },
	['item_Gilbert\'s Message']: { pagename: 'Gilbert\'s Message' },
	['item_Handwritten Letter']: { pagename: 'Handwritten Letter' },
	['item_Hanu\'s Dream Bubble']: { pagename: 'Hanu\'s Dream Bubble' },
	['item_Healing Spray (Small)']: { pagename: 'Healing Spray (Small)' },
	['item_Herta Contract: Roaming Refill']: { pagename: 'Herta Contract: Roaming Refill' },
	['item_Inspo Jade Abacus: Borderland']: { pagename: 'Inspo Jade Abacus: Borderland' },
	['item_Inspo Jade Abacus: Graceful']: { pagename: 'Inspo Jade Abacus: Graceful' },
	['item_Inspo Jade Abacus: Metrical']: { pagename: 'Inspo Jade Abacus: Metrical' },
	['item_Jade Tracer']: { pagename: 'Jade Tracer' },
	['item_Julian\'s Time Capsule']: { pagename: 'Julian\'s Time Capsule' },
	['item_Junjun, the Cuddly Bear']: { pagename: 'Junjun, the Cuddly Bear' },
	['item_Kluzer\'s Letter']: { pagename: 'Kluzer\'s Letter' },
	['item_Liquid Armor']: { pagename: 'Liquid Armor' },
	['item_Liquid Fury']: { pagename: 'Liquid Fury' },
	['item_Logistic Navigation Map']: { pagename: 'Logistic Navigation Map' },
	['item_Lost Lightdust']: { pagename: 'Lost Lightdust' },
	['item_Lucent Afterglow']: { pagename: 'Lucent Afterglow' },
	['item_Luocha\'s Paper Flower']: { pagename: 'Luocha\'s Paper Flower' },
	['item_Marquise']: { pagename: 'Marquise' },
	['item_Mini-Neutron Bomb']: { pagename: 'Mini-Neutron Bomb' },
	['item_Misdelivered Letter 1']: { pagename: 'Misdelivered Letter 1' },
	['item_Misdelivered Letter 2']: { pagename: 'Misdelivered Letter 2' },
	['item_Misdelivered Letter 3']: { pagename: 'Misdelivered Letter 3' },
	['item_Misdelivered Letter 4']: { pagename: 'Misdelivered Letter 4' },
	['item_Momentary Freedom']: { pagename: 'Momentary Freedom' },
	['item_Old Photo of Balakin']: { pagename: 'Old Photo of Balakin' },
	['item_Peppy']: { pagename: 'Peppy (Profile Picture)' },
	['item_Perfect Geomarrow Crystal']: { pagename: 'Perfect Geomarrow Crystal' },
	['item_Pharmacological Studies on the Draught of Draconic Surge']: { pagename: 'Pharmacological Studies on the Draught of Draconic Surge' },
	['item_Photo With March 7th']: { pagename: 'Photo With March 7th' },
	['item_Puffergoat Belly Bliss']: { pagename: 'Puffergoat Belly Bliss' },
	['item_Qingni\'s Memories']: { pagename: 'Qingni\'s Memories' },
	['item_Red Signal Log']: { pagename: 'Red Signal Log' },
	['item_Refreshing Coffee']: { pagename: 'Refreshing Coffee' },
	['item_Research Records "Bribing"']: { pagename: 'Research Records "Bribing"' },
	['item_Research Records "Intimidating"']: { pagename: 'Research Records "Intimidating"' },
	['item_Research Records "Pretend to Be an Officer"']: { pagename: 'Research Records "Pretend to Be an Officer"' },
	['item_Research Records "Sincere Request"']: { pagename: 'Research Records "Sincere Request"' },
	['item_Research Records "Title Page"']: { pagename: 'Research Records "Title Page"' },
	['item_Research Records "Trying to Persuade"']: { pagename: 'Research Records "Trying to Persuade"' },
	['item_Robot Shell']: { pagename: 'Robot Shell' },
	['item_Shattered Jade Seal']: { pagename: 'Shattered Jade Seal' },
	['item_Soulheal Special Mix']: { pagename: 'Soulheal Special Mix' },
	['item_Space Station Special Permit']: { pagename: 'Space Station Special Permit' },
	['item_Special Autoradiograph']: { pagename: 'Special Autoradiograph' },
	['item_Stainless Steel Plaque']: { pagename: 'Stainless Steel Plaque' },
	['item_Steamed puffergoat milk bought for Bailu']: { pagename: 'Steamed puffergoat milk bought for Bailu' },
	['item_Strange Drill Ornament']: { pagename: 'Strange Drill Ornament' },
	['item_Suncake']: { pagename: 'Suncake' },
	['item_Sunshine']: { pagename: 'Sunshine' },
	['item_Terminal Encryption Key']: { pagename: 'Terminal Encryption Key' },
	['item_The Moment of Betrayal']: { pagename: 'The Moment of Betrayal' },
	['item_Todd\'s Snack']: { pagename: 'Todd\'s Snack' },
	['item_Trailblaze Timer']: { pagename: 'Trailblaze Timer' },
	['item_Training Certificate']: { pagename: 'Training Certificate' },
	['item_Tranquil Duster']: { pagename: 'Tranquil Duster' },
	['item_Transcribed Scripture']: { pagename: 'Transcribed Scripture' },
	['item_Trash Can']: { pagename: 'Trash Can (Profile Picture)' },
	['item_Travel Encounters']: { pagename: 'Travel Encounters' },
	['item_Treasure Map: Cannon']: { pagename: 'Treasure Map: Cannon' },
	['item_Unclaimed Parcel']: { pagename: 'Unclaimed Parcel' },
	['item_Undelivered Letter']: { pagename: 'Undelivered Letter' },
	['item_Undying Embers']: { pagename: 'Undying Embers' },
	['item_Undying Starlight']: { pagename: 'Undying Starlight' },
	['item_Videotape: Dim Blue Dot']: { pagename: 'Videotape: Dim Blue Dot' },
	['item_Videotape: Doomsday']: { pagename: 'Videotape: Doomsday' },
	['item_Videotape: Justice']: { pagename: 'Videotape: Justice' },
	['item_Wanted Poster']: { pagename: 'Wanted Poster (Profile Picture)' },
	['item_Wayfare\'s Blessing']: { pagename: 'Wayfare\'s Blessing' },
	['item_Weapon Shards']: { pagename: 'Weapon Shards' },
	['item_Wen Furui\'s Gift']: { pagename: 'Wen Furui\'s Gift' },
	['item_Wild Balaclava']: { pagename: 'Wild Balaclava' },
	['item_Wubbaboo']: { pagename: 'Wubbaboo (Profile Picture)' },
	['item_Yongren\'s Documentation']: { pagename: 'Yongren\'s Documentation' },
	['mission_1000101']: { pagename: 'Chaos In the Deep' },
	['mission_1000201']: { pagename: 'Eye of the Storm' },
	['mission_1000300']: { pagename: 'A Moment of Peace' },
	['mission_1000400']: { pagename: 'Lingering Shadows' },
	['mission_1000402']: { pagename: 'The Voyage Continues' },
	['mission_1010001']: { pagename: 'Drifting Between the Stars' },
	['mission_1010002']: { pagename: 'A Grand Cool Adventure' },
	['mission_1010101']: { pagename: 'Travelers on a Winter Night' },
	['mission_1010201']: { pagename: 'Everwinter Night' },
	['mission_1010301']: { pagename: 'You Can Run, But You Can\'t Hide' },
	['mission_1010401']: { pagename: 'Hide-and-Seek' },
	['mission_1010402']: { pagename: 'The Eighth and Final Rule' },
	['mission_1010403']: { pagename: 'Long Wait for the Blade\'s Edge' },
	['mission_1010501']: { pagename: 'Ones Fallen Into the Abyss' },
	['mission_1010601']: { pagename: 'A Sunset Rendezvous' },
	['mission_1010700']: { pagename: 'The Past Will Return as an Avalanche' },
	['mission_1010801']: { pagename: 'Lying in Rust' },
	['mission_1010901']: { pagename: 'To Rot or to Burn' },
	['mission_1011001']: { pagename: 'Not Good With Farewells' },
	['mission_1011002']: { pagename: 'Cleanse in the Darkness Outside' },
	['mission_1011101']: { pagename: 'Unattainable Idol' },
	['mission_1011102']: { pagename: 'Young Guard' },
	['mission_1011201']: { pagename: 'Soldiers Stay Silent' },
	['mission_1011301']: { pagename: 'The Stars Are Cold Toys' },
	['mission_1011400']: { pagename: 'Roads to the Past Have Long Been Closed' },
	['mission_1011401']: { pagename: 'The Dawn Here...' },
	['mission_1011402']: { pagename: 'The Return' },
	['mission_1011501']: { pagename: 'In the Dangerous Muddy Swamp' },
	['mission_1011502']: { pagename: 'No Time for Me, My Friend' },
	['mission_1011503']: { pagename: 'Silent Galaxy' },
	['mission_1020101']: { pagename: 'An Invitation Without Proffer' },
	['mission_1020201']: { pagename: 'Amidst the Mara-Struck' },
	['mission_1020301']: { pagename: 'Devising Stratagems' },
	['mission_1020400']: { pagename: 'Scattered Memories of Hooded Past' },
	['mission_1020501']: { pagename: 'The Hound Chases the Fox' },
	['mission_1020601']: { pagename: 'Stars Spun, Prescience Sprung' },
	['mission_1020702']: { pagename: 'New Friends Bring New Joy' },
	['mission_1020801']: { pagename: 'Omniscient Inquiry of Arcana' },
	['mission_1020901']: { pagename: 'Tranquil Amidst Turmoil' },
	['mission_1021001']: { pagename: 'Wood Sprouts Anew, Fate Tilts Askew' },
	['mission_1021101']: { pagename: 'Humming Antlers, Entwined Horns' },
	['mission_1021201']: { pagename: 'Desolate Depths of Despair' },
	['mission_1021301']: { pagename: 'Dragon Mislay, Dreams Astray' },
	['mission_1021401']: { pagename: 'Oblation Obtained, Order Ordained' },
	['mission_1021501']: { pagename: 'A Dragon Gallant, Its Ocean Distant' },
	['mission_1021601']: { pagename: 'Demise of Immortality, Finale of Calamity' },
	['mission_1021702']: { pagename: 'Obsequies Performed, A Long Road Ahead' },
	['mission_1030101']: { pagename: 'Long Day\'s Journey Into Night' },
	['mission_1030102']: { pagename: 'The Knocking at Ungodly Hours' },
	['mission_1030201']: { pagename: 'The Youths Who Chase Dreams' },
	['mission_1030301']: { pagename: 'Sleepless Night' },
	['mission_1030302']: { pagename: 'Tales from the Golden Age' },
	['mission_1030303']: { pagename: 'Good Omen, My Friend' },
	['mission_1030304']: { pagename: 'Lullaby of the North Wind' },
	['mission_1030401']: { pagename: 'Gentleness, the Name of Nocturne' },
	['mission_1030501']: { pagename: 'Through a Glass Darkly' },
	['mission_1030601']: { pagename: 'Should One Awaken at Midnight' },
	['mission_1030701']: { pagename: 'Whodunit' },
	['mission_1030901']: { pagename: 'The Devil in Velvet' },
	['mission_1031001']: { pagename: 'Lost Generation' },
	['mission_1031101']: { pagename: 'Double Indemnity' },
	['mission_1031201']: { pagename: 'When the Sacred Ginmill Closes' },
	['mission_1031401']: { pagename: 'Heaven is a Place on Earth' },
	['mission_1031501']: { pagename: 'Why Do the Heathen Rage?' },
	['mission_1031601']: { pagename: 'The Tell-Tale Heart' },
	['mission_1031701']: { pagename: 'All the Sad Tales' },
	['mission_1031801']: { pagename: 'A Walk Among the Tombstones' },
	['mission_2000801']: { pagename: 'Night of Universal Hallucinations' },
	['mission_2000901']: { pagename: 'Mundane Troubles' },
	['mission_2000902']: { pagename: 'Memory Backtrack' },
	['mission_2001001']: { pagename: 'When the Stars of Ingenuity Shine' },
	['mission_2010201']: { pagename: 'Future Market (Prologue)' },
	['mission_2010202']: { pagename: 'Future Market (I)' },
	['mission_2010203']: { pagename: 'Future Market (II)' },
	['mission_2020103']: { pagename: 'Venom Brews, Immortality Looms' },
	['mission_2020104']: { pagename: 'Sinners Misled, Credence Falsified' },
	['mission_2020307']: { pagename: 'A Knight Stranger' },
	['mission_2020317']: { pagename: 'Ten-Lords\' Decree and Calamity\'s Remnant' },
	['mission_2020901']: { pagename: 'Poetic Genius Ingenium' },
	['mission_2021001']: { pagename: 'Clouds Leave No Trace' },
	['mission_2021701']: { pagename: 'Sojourners\' Ghastly Reverie' },
	['mission_2030001']: { pagename: 'Cosmic Star' },
	['mission_2030101']: { pagename: 'Envision a Rose Forthcoming' },
	['mission_2030201']: { pagename: 'Goodness Is Rare' },
	['mission_2030301']: { pagename: 'The Trees At Peace' },
	['mission_3000800']: { pagename: 'Space Station Ghost Stories' },
	['mission_3000801']: { pagename: 'Space Station Ghost Stories: Rowdy Security Door' },
	['mission_3000803']: { pagename: 'Space Station Ghost Stories: Fortune Leaf' },
	['mission_4015401']: { pagename: 'Pathfinder' },
	['mission_4020101']: { pagename: 'Trial of Equilibrium: Part One' },
	['mission_4020102']: { pagename: 'Trial of Equilibrium: Part Two' },
	['mission_4020103']: { pagename: 'Trial of Equilibrium: Part Three' },
	['mission_4020104']: { pagename: 'Trial of Equilibrium: Part Four' },
	['mission_4020105']: { pagename: 'Trial of Equilibrium: Part Five' },
	['mission_4020106']: { pagename: 'Trial of Equilibrium: Part Six' },
	['mission_4030001']: { pagename: 'Simulated Universe: First Closed Beta' },
	['mission_4040302']: { pagename: 'Big Fish, Tiny Pond (I)' },
	['mission_4040306']: { pagename: 'Thirteen Clocks' },
	['mission_4040334']: { pagename: 'Big Fish, Tiny Pond (II)' },
	['mission_4050011']: { pagename: 'The Lost Button' },
	['mission_4050013']: { pagename: 'Leisure Time' },
	['mission_4050016']: { pagename: 'Express Regulations: Pets on Board' },
	['mission_4050018']: { pagename: 'Space Plant' },
	['mission_4050020']: { pagename: 'Pom-Pom With a Stiff Neck' },
	['mission_4050021']: { pagename: 'Stiff Pom-Pom' },
	['mission_4050022']: { pagename: 'Talk to Me' },
	['mission_4050023']: { pagename: 'Reflective Floor' },
	['mission_4050024']: { pagename: 'Friends on the Space Station' },
	['mission_4050025']: { pagename: 'Light Design in the Express' },
	['mission_4122102']: { pagename: 'Eye of the Cosmos Part II' },
	['mission_4122103']: { pagename: 'Eye of the Cosmos Part III' },
	['mission_4240301']: { pagename: 'Clockwork: Poseman' },
	['mission_4240302']: { pagename: 'Clockwork: Mullich' },
	['mission_4240304']: { pagename: 'Clockwork: Chabro' },
	['mission_4240305']: { pagename: 'Clockwork: Quinn' },
	['mission_4240316']: { pagename: 'Clockwork: Go-Ray' },
	['mission_4240306']: { pagename: 'Clockwork: Colleen' },
	['mission_4240307']: { pagename: 'Clockwork: Benny' },
	['mission_4240308']: { pagename: 'Clockwork: Bocchi' },
	['mission_4240309']: { pagename: 'Clockwork: Emmrich' },
	['mission_4240310']: { pagename: 'Clockwork: Morris' },
	['mission_4240311']: { pagename: 'Clockwork: Forla' },
	['mission_4240312']: { pagename: 'Clockwork: Larose' },
	['mission_4240313']: { pagename: 'Clockwork: Lew Archer' },
	['mission_4240314']: { pagename: 'Clockwork: IV' },
	['mission_4240320']: { pagename: 'Clockwork: Whisper' },
	['mission_4240321']: { pagename: 'Clockwork: Mr. McCoy' },
	['mission_4240322']: { pagename: 'Clockwork: Oksana' },
	['mission_8003101']: { pagename: 'Space Station Task Force (Mission)' },
	['mission_8014121']: { pagename: 'Hyperlink Match, Wen Shiling!' },
	['mission_8014122']: { pagename: 'Hyperlink Match, Julian!' },
	['mission_8014123']: { pagename: 'Hyperlink Match, Dunn!' },
	['mission_8014124']: { pagename: 'Hyperlink Match, Oleg!' },
	['mission_8014125']: { pagename: 'Hyperlink Match, Natasha!' },
	['mission_8014126']: { pagename: 'Hyperlink Match, Clara!' },
	['mission_8014127']: { pagename: 'Hyperlink Match, Gepard!' },
	['mission_8014128']: { pagename: 'Hyperlink Match, Lynx!' },
	['mission_8014129']: { pagename: 'Hyperlink Match, Arlan!' },
	['mission_8014130']: { pagename: 'Hyperlink Match, Asta!' },
	['mission_8014131']: { pagename: 'Hyperlink Match, Diting!' },
	['mission_8014132']: { pagename: 'Hyperlink Match, Yanqing!' },
	['mission_8014133']: { pagename: 'Hyperlink Match, Qingque!' },
	['mission_8014134']: { pagename: 'Hyperlink Match, Peppy!' },
	['mission_8014135']: { pagename: 'Hyperlink Match, Sampo!' },
	['mission_8014136']: { pagename: 'Hyperlink Match, Bronya!' },
	['mission_8014137']: { pagename: 'Hyperlink Match, Welt!' },
	['mission_8014138']: { pagename: 'Hyperlink Match, Topaz!' },
	['mission_8014139']: { pagename: 'Hyperlink Match, Wilder!' },
	['mission_8014140']: { pagename: 'Hyperlink Match, March 7th!' },
	['mission_8014161']: { pagename: 'Planar Infinity (Mission)' },
	['mission_8015101']: { pagename: 'Twins' },
	['mission_8015102']: { pagename: 'Percipient' },
	['mission_8015103']: { pagename: 'Sword Essence' },
	['mission_8015104']: { pagename: 'Foxian Dream' },
	['mission_8015150']: { pagename: 'Exorcismal Chronicle' },
	['mission_8015152']: { pagename: 'Luofu Myths: Chess Ghost' },
	['mission_8015157']: { pagename: 'Luofu Myths: Haunted House' },
	['mission_8015191']: { pagename: 'Fyxestroll Gathering (I)' },
	['mission_8015192']: { pagename: 'Fyxestroll Gathering (II)' },
	['mission_8015193']: { pagename: 'Fyxestroll Gathering (III)' },
	['mission_8015194']: { pagename: 'Fyxestroll Gathering (IV)' },
	['mission_8016101']: { pagename: 'Gold and Gears: The Beginning' },
	['mission_8016102']: { pagename: 'Gold and Gears: Experimental Teaching' },
	['mission_8016103']: { pagename: 'Gold and Gears: IPC Secrets (I)' },
	['mission_8016104']: { pagename: 'Gold and Gears: IPC Secrets (II)' },
	['mission_8016105']: { pagename: 'Gold and Gears: Finale' },
	['mission_8016106']: { pagename: 'Gold and Gears: Testing Goals' },
	['mission_8017101']: { pagename: 'Youci\'s Clever Decor' },
	['mission_8020233']: { pagename: 'Slaughterhouse' },
	['mission_8020300']: { pagename: 'Dreamjolt TV (Adventure Mission)' },
	['mission_8021100']: { pagename: 'Become A Drinksmith' },
	['mission_8021101']: { pagename: 'Morose Monsters (I)' },
	['mission_8021102']: { pagename: 'Morose Monsters (II)' },
	['mission_8021103']: { pagename: 'Morose Monsters (III)' },
	['mission_8021104']: { pagename: 'Morose Monsters (IV)' },
	['mission_8021105']: { pagename: 'Morose Monsters (V)' },
	['mission_8021106']: { pagename: 'Morose Monsters (VI)' },
	['mission_8021201']: { pagename: 'Tides of War (Adventure Mission)' },
	['mission_8021301']: { pagename: 'Package for the Nameless' },
	['mission_8021302']: { pagename: 'Package to the Nameless' },
	['mission_A Friend in Need Is a Friend Indeed']: { pagename: 'A Friend in Need Is a Friend Indeed' },
	['mission_A Gift From Xianzhou']: { pagename: 'A Gift From Xianzhou' },
	['mission_A Marvelous Night at Boulder Town']: { pagename: 'A Marvelous Night at Boulder Town' },
	['mission_A Teacher and a Friend']: { pagename: 'A Teacher and a Friend' },
	['mission_A Teacher and a Friend: Continued']: { pagename: 'A Teacher and a Friend: Continued' },
	['mission_A Teacher and a Friend: Interlude']: { pagename: 'A Teacher and a Friend: Interlude' },
	['mission_All About Tamila']: { pagename: 'All About Tamila' },
	['mission_An Eye for an Eye']: { pagename: 'An Eye for an Eye' },
	['mission_An Eye for an Eye (Part 2)']: { pagename: 'An Eye for an Eye (Part 2)' },
	['mission_An Eye for an Eye (Part 3)']: { pagename: 'An Eye for an Eye (Part 3)' },
	['mission_An Unexpected Turn of Events']: { pagename: 'An Unexpected Turn of Events' },
	['mission_Ancestor\'s Drill Bit']: { pagename: 'Ancestor\'s Drill Bit' },
	['mission_Anomaly Detection 1']: { pagename: 'Anomaly Detection 1' },
	['mission_Anomaly Detection 2']: { pagename: 'Anomaly Detection 2' },
	['mission_Anomaly Detection 3']: { pagename: 'Anomaly Detection 3' },
	['mission_Anomaly Detection 4']: { pagename: 'Anomaly Detection 4' },
	['mission_Anomaly Detection 5']: { pagename: 'Anomaly Detection 5' },
	['mission_Anomaly Detection 6']: { pagename: 'Anomaly Detection 6' },
	['mission_Anomaly Detection 7']: { pagename: 'Anomaly Detection 7' },
	['mission_Back in Business (I)']: { pagename: 'Back in Business (I)' },
	['mission_Back in Business (II)']: { pagename: 'Back in Business (II)' },
	['mission_Back in Business (III)']: { pagename: 'Back in Business (III)' },
	['mission_Back in Business (IV)']: { pagename: 'Back in Business (IV)' },
	['mission_Battle for Health']: { pagename: 'Battle for Health' },
	['mission_Battle of Wits! Herta Space Station!']: { pagename: 'Battle of Wits! Herta Space Station!' },
	['mission_Being Human 101']: { pagename: 'Being Human 101' },
	['mission_Bestial Ferocity']: { pagename: 'Bestial Ferocity' },
	['mission_Bestial Ferocity: The End']: { pagename: 'Bestial Ferocity: The End' },
	['mission_Blizzard Immunity']: { pagename: 'Blizzard Immunity' },
	['mission_Bored to Death']: { pagename: 'Bored to Death' },
	['mission_Calyx (Crimson): Bud of Harmony']: { pagename: 'Calyx (Crimson): Bud of Harmony (Adventure Mission)' },
	['mission_Calyx (Golden): Bud of Memories']: { pagename: 'Calyx (Golden): Bud of Memories (Adventure Mission)' },
	['mission_Catch Me If You Can']: { pagename: 'Catch Me If You Can' },
	['mission_Cavern of Corrosion']: { pagename: 'Cavern of Corrosion (Adventure Mission)' },
	['mission_Clash! Great Mine!']: { pagename: 'Clash! Great Mine!' },
	['mission_Critter Pick: Care']: { pagename: 'Critter Pick: Care' },
	['mission_Critter Pick: Detective Peppy Interlude']: { pagename: 'Critter Pick: Detective Peppy Interlude' },
	['mission_Critter Pick: New Dining Area']: { pagename: 'Critter Pick: New Dining Area' },
	['mission_Critter Pick: Nurture']: { pagename: 'Critter Pick: Nurture' },
	['mission_Critter Pick: Rest Area']: { pagename: 'Critter Pick: Rest Area' },
	['mission_Critter Pick: Reunion']: { pagename: 'Critter Pick: Reunion' },
	['mission_Custom Orders (Adventure Mission)']: { pagename: 'Custom Orders (Adventure Mission)' },
	['mission_Deep "Bubble Pinball" Difficulty I']: { pagename: 'Deep "Bubble Pinball" Difficulty I' },
	['mission_Deep "Bubble Pinball" Difficulty II']: { pagename: 'Deep "Bubble Pinball" Difficulty II' },
	['mission_Deep "Bubble Pinball" Difficulty III']: { pagename: 'Deep "Bubble Pinball" Difficulty III' },
	['mission_Deep "Bubble Pinball" Difficulty IV']: { pagename: 'Deep "Bubble Pinball" Difficulty IV' },
	['mission_Deep "Bubble Pinball" Difficulty V']: { pagename: 'Deep "Bubble Pinball" Difficulty V' },
	['mission_Deep "Dream Ticker" Difficulty I']: { pagename: 'Deep "Dream Ticker" Difficulty I' },
	['mission_Deep "Dream Ticker" Difficulty II']: { pagename: 'Deep "Dream Ticker" Difficulty II' },
	['mission_Deep "Dream Ticker" Difficulty III']: { pagename: 'Deep "Dream Ticker" Difficulty III' },
	['mission_Deep "Dream Ticker" Difficulty IV']: { pagename: 'Deep "Dream Ticker" Difficulty IV' },
	['mission_Deep "Dream Ticker" Difficulty V']: { pagename: 'Deep "Dream Ticker" Difficulty V' },
	['mission_Deep "Dreamwalker" Difficulty I']: { pagename: 'Deep "Dreamwalker" Difficulty I' },
	['mission_Deep "Dreamwalker" Difficulty II']: { pagename: 'Deep "Dreamwalker" Difficulty II' },
	['mission_Deep "Hanu\'s Adventure" Difficulty I']: { pagename: 'Deep "Hanu\'s Adventure" Difficulty I' },
	['mission_Deep "Hanu\'s Adventure" Difficulty II']: { pagename: 'Deep "Hanu\'s Adventure" Difficulty II' },
	['mission_Dock Operations (I)']: { pagename: 'Dock Operations (I)' },
	['mission_Dock Operations (II)']: { pagename: 'Dock Operations (II)' },
	['mission_Dock Operations (III)']: { pagename: 'Dock Operations (III)' },
	['mission_Don\'t Forget About Home']: { pagename: 'Don\'t Forget About Home' },
	['mission_Dreams and the Art of Clock Maintenance (I)']: { pagename: 'Dreams and the Art of Clock Maintenance (I)' },
	['mission_Echo of War']: { pagename: 'Echo of War (Adventure Mission)' },
	['mission_Embark! Corridor of Fading Echoes!']: { pagename: 'Embark! Corridor of Fading Echoes!' },
	['mission_Emptiness of Locus Silentii']: { pagename: 'Emptiness of Locus Silentii' },
	['mission_Eternal Freeze Aftermath']: { pagename: 'Eternal Freeze Aftermath' },
	['mission_Evanesce Like the Morning Dew']: { pagename: 'Evanesce Like the Morning Dew' },
	['mission_Evening Chats on the Luofu']: { pagename: 'Evening Chats on the Luofu' },
	['mission_Ever-Changing']: { pagename: 'Ever-Changing' },
	['mission_Excessive Shedding']: { pagename: 'Excessive Shedding' },
	['mission_Exhibit Collection: Automaton Beetle']: { pagename: 'Exhibit Collection: Automaton Beetle' },
	['mission_Exhibit Collection: Automaton Hound']: { pagename: 'Exhibit Collection: Automaton Hound' },
	['mission_Exhibit Collection: Automaton Spider']: { pagename: 'Exhibit Collection: Automaton Spider' },
	['mission_Exhibit Collection: Cannon']: { pagename: 'Exhibit Collection: Cannon' },
	['mission_Exhibit Collection: Information Terminal and Display Monitor Set']: { pagename: 'Exhibit Collection: Information Terminal and Display Monitor Set' },
	['mission_Exhibit Collection: Mechanism Energy Hub']: { pagename: 'Exhibit Collection: Mechanism Energy Hub' },
	['mission_Exhibit Collection: Oil Painting Part 1']: { pagename: 'Exhibit Collection: Oil Painting Part 1' },
	['mission_Exhibit Collection: Oil Painting Part 2']: { pagename: 'Exhibit Collection: Oil Painting Part 2' },
	['mission_Exhibit Collection: Oil Painting Part 3']: { pagename: 'Exhibit Collection: Oil Painting Part 3' },
	['mission_Exhibit Collection: Portrait of the Supreme Guardian']: { pagename: 'Exhibit Collection: Portrait of the Supreme Guardian' },
	['mission_Exhibit Replica: Alisa Rand\'s Lance']: { pagename: 'Exhibit Replica: Alisa Rand\'s Lance' },
	['mission_Exhibit Replica: Antimatter Legion Part 1']: { pagename: 'Exhibit Replica: Antimatter Legion Part 1' },
	['mission_Exhibit Replica: Antimatter Legion Part 2']: { pagename: 'Exhibit Replica: Antimatter Legion Part 2' },
	['mission_Exhibit Replica: Trailblazer\'s Ball Bat']: { pagename: 'Exhibit Replica: Trailblazer\'s Ball Bat' },
	['mission_Exhibit Restoration: Antique Desk Lamp']: { pagename: 'Exhibit Restoration: Antique Desk Lamp' },
	['mission_Exhibit Restoration: Antique Radio']: { pagename: 'Exhibit Restoration: Antique Radio' },
	['mission_Exhibit Restoration: Automaton Control Terminal']: { pagename: 'Exhibit Restoration: Automaton Control Terminal' },
	['mission_Exhibit Restoration: Mine Mantel Clock']: { pagename: 'Exhibit Restoration: Mine Mantel Clock' },
	['mission_Experimental Report 1']: { pagename: 'Experimental Report 1' },
	['mission_Experimental Report 2']: { pagename: 'Experimental Report 2' },
	['mission_Experimental Report 3']: { pagename: 'Experimental Report 3' },
	['mission_Experimental Report 4']: { pagename: 'Experimental Report 4' },
	['mission_Experimental Report 5']: { pagename: 'Experimental Report 5' },
	['mission_Experimental Report 6']: { pagename: 'Experimental Report 6' },
	['mission_Experimental Report 7']: { pagename: 'Experimental Report 7' },
	['mission_Express Humidity']: { pagename: 'Express Humidity' },
	['mission_Express Regulations: Management Experience']: { pagename: 'Express Regulations: Management Experience' },
	['mission_Eye of the Cosmos']: { pagename: 'Eye of the Cosmos' },
	['mission_Farther Than The Snow Plains']: { pagename: 'Farther Than The Snow Plains' },
	['mission_Final Showdown! Intergalactic Celebration!']: { pagename: 'Final Showdown! Intergalactic Celebration!' },
	['mission_Fired']: { pagename: 'Fired' },
	['mission_Fleeting Lights']: { pagename: 'Fleeting Lights' },
	['mission_Fly to Tomorrow']: { pagename: 'Fly to Tomorrow' },
	['mission_Food Fest Day Five']: { pagename: 'Food Fest Day Five' },
	['mission_Food Fest Day Four']: { pagename: 'Food Fest Day Four' },
	['mission_Food Fest Day One']: { pagename: 'Food Fest Day One' },
	['mission_Food Fest Day Seven']: { pagename: 'Food Fest Day Seven' },
	['mission_Food Fest Day Six']: { pagename: 'Food Fest Day Six' },
	['mission_Food Fest Day Three']: { pagename: 'Food Fest Day Three' },
	['mission_Food Fest Day Two']: { pagename: 'Food Fest Day Two' },
	['mission_For I Have Touched the Sky']: { pagename: 'For I Have Touched the Sky' },
	['mission_From Xianzhou With Love']: { pagename: 'From Xianzhou With Love' },
	['mission_Frosty Blade\'s Trial']: { pagename: 'Frosty Blade\'s Trial' },
	['mission_Ghost of the Past']: { pagename: 'Ghost of the Past' },
	['mission_Ghost-Hunting Squad']: { pagename: 'Ghost-Hunting Squad' },
	['mission_Ghost-Hunting Squad: Excess Is as Bad as Deficiency']: { pagename: 'Ghost-Hunting Squad: Excess Is as Bad as Deficiency' },
	['mission_Ghost-Hunting Squad: Gold Medallion']: { pagename: 'Ghost-Hunting Squad: Gold Medallion' },
	['mission_Ghost-Hunting Squad: Silver Medallion']: { pagename: 'Ghost-Hunting Squad: Silver Medallion' },
	['mission_Gladiator']: { pagename: 'Gladiator' },
	['mission_Good Stuff']: { pagename: 'Good Stuff' },
	['mission_Grinding in the Dark']: { pagename: 'Grinding in the Dark' },
	['mission_Guardian of the Shoreline']: { pagename: 'Guardian of the Shoreline' },
	['mission_Guide Paradox']: { pagename: 'Guide Paradox' },
	['mission_Hanu\'s Prison Break']: { pagename: 'Hanu\'s Prison Break (Adventure Mission)' },
	['mission_Height Measurement']: { pagename: 'Height Measurement' },
	['mission_Hiring Guides: Gepard']: { pagename: 'Hiring Guides: Gepard' },
	['mission_Hiring Guides: Hook']: { pagename: 'Hiring Guides: Hook' },
	['mission_Hiring Guides: Natasha']: { pagename: 'Hiring Guides: Natasha' },
	['mission_Hiring Guides: Seele']: { pagename: 'Hiring Guides: Seele' },
	['mission_Hiring Guides: Serval']: { pagename: 'Hiring Guides: Serval' },
	['mission_Hook\'s Gift']: { pagename: 'Hook\'s Gift' },
	['mission_Hook\'s Treasure']: { pagename: 'Hook\'s Treasure' },
	['mission_It All Started With a Man and a Dog (I)']: { pagename: 'It All Started With a Man and a Dog (I)' },
	['mission_It All Started With a Man and a Dog (II)']: { pagename: 'It All Started With a Man and a Dog (II)' },
	['mission_It All Started With a Man and a Dog (III)']: { pagename: 'It All Started With a Man and a Dog (III)' },
	['mission_Juice Recipe']: { pagename: 'Juice Recipe' },
	['mission_Lesley Dean\'s Synesthesia Dreamscape']: { pagename: 'Lesley Dean\'s Synesthesia Dreamscape' },
	['mission_Let\'s Go! Aetherium Wars!']: { pagename: 'Let\'s Go! Aetherium Wars!' },
	['mission_Letter from a Strange Woman']: { pagename: 'Letter from a Strange Woman' },
	['mission_Looking For A Disk']: { pagename: 'Looking For A Disk' },
	['mission_Luofu Myths: Ghostly Call']: { pagename: 'Luofu Myths: Ghostly Call' },
	['mission_Luofu Myths: Moon Impaler Skiff']: { pagename: 'Luofu Myths: Moon Impaler Skiff' },
	['mission_Luofu Myths: Pillow Whisper']: { pagename: 'Luofu Myths: Pillow Whisper' },
	['mission_Luofu Myths: Soul Departure']: { pagename: 'Luofu Myths: Soul Departure' },
	['mission_Luofu Myths: Soul Departure (Continued)']: { pagename: 'Luofu Myths: Soul Departure (Continued)' },
	['mission_Luofu Myths: Specterlight Records']: { pagename: 'Luofu Myths: Specterlight Records' },
	['mission_Luofu Myths: Specterlight Records (Continued)']: { pagename: 'Luofu Myths: Specterlight Records (Continued)' },
	['mission_Martialist Fighters']: { pagename: 'Martialist Fighters' },
	['mission_Masquerade Duet']: { pagename: 'Masquerade Duet' },
	['mission_Meals Are More Important']: { pagename: 'Meals Are More Important' },
	['mission_Merchant Event: Delicacy Pavilion']: { pagename: 'Merchant Event: Delicacy Pavilion' },
	['mission_Merchant Event: Du\'s Teahouse']: { pagename: 'Merchant Event: Du\'s Teahouse' },
	['mission_Merchant Event: Elegance Pagoda']: { pagename: 'Merchant Event: Elegance Pagoda' },
	['mission_Merchant Event: Food Stand']: { pagename: 'Merchant Event: Food Stand' },
	['mission_Merchant Event: Longevity Hall']: { pagename: 'Merchant Event: Longevity Hall' },
	['mission_Merchant Event: Mr. Huo']: { pagename: 'Merchant Event: Mr. Huo' },
	['mission_Mo Cuishle']: { pagename: 'Mo Cuishle' },
	['mission_New Teas Coming Up']: { pagename: 'New Teas Coming Up' },
	['mission_Night on the Great Mine (Part 1)']: { pagename: 'Night on the Great Mine (Part 1)' },
	['mission_Night on the Great Mine (Part 2)']: { pagename: 'Night on the Great Mine (Part 2)' },
	['mission_Night on the Great Mine (Part 3)']: { pagename: 'Night on the Great Mine (Part 3)' },
	['mission_No One Is Answering']: { pagename: 'No One Is Answering' },
	['mission_Old Foreman\'s Treasure']: { pagename: 'Old Foreman\'s Treasure' },
	['mission_Old Fortress Scavenge']: { pagename: 'Old Fortress Scavenge' },
	['mission_On the Doorsteps of Science']: { pagename: 'On the Doorsteps of Science' },
	['mission_Only A Child']: { pagename: 'Only A Child' },
	['mission_Onward! Cloudford!']: { pagename: 'Onward! Cloudford!' },
	['mission_Operation Mole']: { pagename: 'Operation Mole' },
	['mission_Opportunity Makes the Thief (Part 1)']: { pagename: 'Opportunity Makes the Thief (Part 1)' },
	['mission_Opportunity Makes the Thief (Part 2)']: { pagename: 'Opportunity Makes the Thief (Part 2)' },
	['mission_Opportunity Makes the Thief (Part 3)']: { pagename: 'Opportunity Makes the Thief (Part 3)' },
	['mission_Opportunity Makes the Thief (Part 4)']: { pagename: 'Opportunity Makes the Thief (Part 4)' },
	['mission_Origin of the Medicine']: { pagename: 'Origin of the Medicine' },
	['mission_Out of Control']: { pagename: 'Out of Control' },
	['mission_Out of Reach']: { pagename: 'Out of Reach' },
	['mission_Out of Thin Air Guide']: { pagename: 'Out of Thin Air Guide' },
	['mission_Outsourcer']: { pagename: 'Outsourcer' },
	['mission_Pallbearing Merchant, Swordwielding Recruit']: { pagename: 'Pallbearing Merchant, Swordwielding Recruit' },
	['mission_Pom-Pom\'s Score']: { pagename: 'Pom-Pom\'s Score' },
	['mission_Punklorde Mentality']: { pagename: 'Punklorde Mentality' },
	['mission_Rarely Affectionate (Part 1)']: { pagename: 'Rarely Affectionate (Part 1)' },
	['mission_Rarely Affectionate (Part 2)']: { pagename: 'Rarely Affectionate (Part 2)' },
	['mission_Requiem Mass']: { pagename: 'Requiem Mass' },
	['mission_Ring and Stage I']: { pagename: 'Ring and Stage I' },
	['mission_Ring and Stage II']: { pagename: 'Ring and Stage II' },
	['mission_Road to Renewal: General Hall Part 1']: { pagename: 'Road to Renewal: General Hall Part 1' },
	['mission_Road to Renewal: General Hall Part 2']: { pagename: 'Road to Renewal: General Hall Part 2' },
	['mission_Road to Renewal: History-Culture Hall']: { pagename: 'Road to Renewal: History-Culture Hall' },
	['mission_Road to Renewal: Industrial Hall']: { pagename: 'Road to Renewal: Industrial Hall' },
	['mission_Road to Revival']: { pagename: 'Road to Revival' },
	['mission_Routine Inspection']: { pagename: 'Routine Inspection' },
	['mission_Scout on the Snow Plains']: { pagename: 'Scout on the Snow Plains' },
	['mission_Sealed Sector']: { pagename: 'Sealed Sector' },
	['mission_Sensitive Beings (I)']: { pagename: 'Sensitive Beings (I)' },
	['mission_Sensitive Beings (II)']: { pagename: 'Sensitive Beings (II)' },
	['mission_Sensitive Beings (III)']: { pagename: 'Sensitive Beings (III)' },
	['mission_Shallow "Bubble Pinball" Difficulty I']: { pagename: 'Shallow "Bubble Pinball" Difficulty I' },
	['mission_Shallow "Bubble Pinball" Difficulty II']: { pagename: 'Shallow "Bubble Pinball" Difficulty II' },
	['mission_Shallow "Dream Ticker" Difficulty I']: { pagename: 'Shallow "Dream Ticker" Difficulty I' },
	['mission_Shallow "Dream Ticker" Difficulty II']: { pagename: 'Shallow "Dream Ticker" Difficulty II' },
	['mission_Shallow "Dreamwalker" Difficulty I']: { pagename: 'Shallow "Dreamwalker" Difficulty I' },
	['mission_Shallow "Dreamwalker" Difficulty II']: { pagename: 'Shallow "Dreamwalker" Difficulty II' },
	['mission_Shallow "Hanu\'s Adventure" Difficulty I']: { pagename: 'Shallow "Hanu\'s Adventure" Difficulty I' },
	['mission_Shallow "Hanu\'s Adventure" Difficulty II']: { pagename: 'Shallow "Hanu\'s Adventure" Difficulty II' },
	['mission_Signs of Fragmentum']: { pagename: 'Signs of Fragmentum (Adventure Mission)' },
	['mission_2000204']: { pagename: 'Signs of Fragmentum' },
	['mission_Silent yet Shining']: { pagename: 'Silent yet Shining' },
	['mission_Simulated Universe (Part 1)']: { pagename: 'Simulated Universe (Part 1)' },
	['mission_Simulated Universe (Part 2)']: { pagename: 'Simulated Universe (Part 2)' },
	['mission_Simulated Universe: Second Closed Beta']: { pagename: 'Simulated Universe: Second Closed Beta' },
	['mission_Sleeplessness']: { pagename: 'Sleeplessness' },
	['mission_Space Station Ghost Stories: Vanished Toilet']: { pagename: 'Space Station Ghost Stories: Vanished Toilet' },
	['mission_Spirit Traces']: { pagename: 'Spirit Traces' },
	['mission_Stagnant Shadow']: { pagename: 'Stagnant Shadow (Adventure Mission)' },
	['mission_Stellar Flare: Opening']: { pagename: 'Stellar Flare: Opening' },
	['mission_Stellar Shadowseeker: 1st Stop, Master Control Zone']: { pagename: 'Stellar Shadowseeker: 1st Stop, Master Control Zone' },
	['mission_Stellar Shadowseeker: 2nd Stop, Storage Zone']: { pagename: 'Stellar Shadowseeker: 2nd Stop, Storage Zone' },
	['mission_Stellar Shadowseeker: 3rd Stop, Supply Zone']: { pagename: 'Stellar Shadowseeker: 3rd Stop, Supply Zone' },
	['mission_Stellar Shadowseeker: 4th Stop, Administrative District']: { pagename: 'Stellar Shadowseeker: 4th Stop, Administrative District' },
	['mission_Stellar Shadowseeker: 5th Stop, Boulder Town']: { pagename: 'Stellar Shadowseeker: 5th Stop, Boulder Town' },
	['mission_Stellar Shadowseeker: 6th Stop, Rivet Town']: { pagename: 'Stellar Shadowseeker: 6th Stop, Rivet Town' },
	['mission_Stellar Shadowseeker: 7th Stop, Astral Express']: { pagename: 'Stellar Shadowseeker: 7th Stop, Astral Express' },
	['mission_Stellar Shadowseeker: Photography Practice']: { pagename: 'Stellar Shadowseeker: Photography Practice' },
	['mission_Street Pen Pal']: { pagename: 'Street Pen Pal' },
	['mission_Sudden Sadness']: { pagename: 'Sudden Sadness' },
	['mission_Survival Wisdom']: { pagename: 'Survival Wisdom' },
	['mission_Swarm Disaster: Exchanging Secret Intel']: { pagename: 'Swarm Disaster: Exchanging Secret Intel' },
	['mission_Swarm Disaster: Experimental Teaching (I)']: { pagename: 'Swarm Disaster: Experimental Teaching (I)' },
	['mission_Swarm Disaster: Experimental Teaching (II)']: { pagename: 'Swarm Disaster: Experimental Teaching (II)' },
	['mission_Swarm Disaster: Test Objective']: { pagename: 'Swarm Disaster: Test Objective' },
	['mission_Swarm Disaster: The Beginning']: { pagename: 'Swarm Disaster: The Beginning' },
	['mission_Swarm Disaster: The End']: { pagename: 'Swarm Disaster: The End' },
	['mission_Tale of Woe']: { pagename: 'Tale of Woe' },
	['mission_Tales of the Fantastic: Chapter 1']: { pagename: 'Tales of the Fantastic: Chapter 1' },
	['mission_Tales of the Fantastic: Chapter 2']: { pagename: 'Tales of the Fantastic: Chapter 2' },
	['mission_Tales of the Fantastic: Chapter 3']: { pagename: 'Tales of the Fantastic: Chapter 3' },
	['mission_Taste Test']: { pagename: 'Taste Test' },
	['mission_Technology Changes Lives']: { pagename: 'Technology Changes Lives' },
	['mission_The Adventurous Moles']: { pagename: 'The Adventurous Moles' },
	['mission_The Art of Conversation']: { pagename: 'The Art of Conversation' },
	['mission_The Conductor\'s Rewards']: { pagename: 'The Conductor\'s Rewards' },
	['mission_The Dragon Returns Home']: { pagename: 'The Dragon Returns Home' },
	['mission_The Setting Sun Is the Most Beautiful']: { pagename: 'The Setting Sun Is the Most Beautiful' },
	['mission_Time Express']: { pagename: 'Time Express' },
	['mission_To Eris']: { pagename: 'To Eris' },
	['mission_To: The Faint Star']: { pagename: 'To: The Faint Star' },
	['mission_Todd Riordan\'s Academic Research']: { pagename: 'Todd Riordan\'s Academic Research' },
	['mission_Todd Riordan\'s Academic Research: Continued']: { pagename: 'Todd Riordan\'s Academic Research: Continued' },
	['mission_Todd Riordan\'s Academic Research: Glimpsing the Verdant Apothecary\'s Pouch']: { pagename: 'Todd Riordan\'s Academic Research: Glimpsing the Verdant Apothecary\'s Pouch' },
	['mission_Todd Riordan\'s Academic Research: The Three Draconic Transformations']: { pagename: 'Todd Riordan\'s Academic Research: The Three Draconic Transformations' },
	['mission_Total Recall']: { pagename: 'Total Recall' },
	['mission_Underground Travelogue (Part 1)']: { pagename: 'Underground Travelogue (Part 1)' },
	['mission_Underground Travelogue (Part 2)']: { pagename: 'Underground Travelogue (Part 2)' },
	['mission_Underground Travelogue (Part 3)']: { pagename: 'Underground Travelogue (Part 3)' },
	['mission_Underground Travelogue (Part 4)']: { pagename: 'Underground Travelogue (Part 4)' },
	['mission_Underground Travelogue (Part 5)']: { pagename: 'Underground Travelogue (Part 5)' },
	['mission_Vessel of Mediocrity (Part 1)']: { pagename: 'Vessel of Mediocrity (Part 1)' },
	['mission_Vessel of Mediocrity (Part 2)']: { pagename: 'Vessel of Mediocrity (Part 2)' },
	['mission_Vessel of Mediocrity (Part 3)']: { pagename: 'Vessel of Mediocrity (Part 3)' },
	['mission_Virtual Scentventure']: { pagename: 'Virtual Scentventure (Adventure Mission)' },
	['mission_When Business Comes Knocking']: { pagename: 'When Business Comes Knocking' },
	['mission_Winter Soldiers\' March']: { pagename: 'Winter Soldiers\' March' },
	['mission_Winter Soldiers\' March (Part 1)']: { pagename: 'Winter Soldiers\' March (Part 1)' },
	['mission_Winter Soldiers\' March (Part 2)']: { pagename: 'Winter Soldiers\' March (Part 2)' },
	['mission_Winter Soldiers\' March (Part 3)']: { pagename: 'Winter Soldiers\' March (Part 3)' },
	['mission_Wish You Were Here']: { pagename: 'Wish You Were Here' },
	['mission_Wooo A Little']: { pagename: 'Wooo A Little' },
	['mission_Wraiths of Mirage']: { pagename: 'Wraiths of Mirage' },
	['mission_Wraiths of Mirage: Herding Operation']: { pagename: 'Wraiths of Mirage: Herding Operation' },
	['mission_Wraiths of Mirage: Hunting Operation']: { pagename: 'Wraiths of Mirage: Hunting Operation' },
	['mission_Wraiths of Mirage: Retracing Operation']: { pagename: 'Wraiths of Mirage: Retracing Operation' },
	['mission_You Already Know Me']: { pagename: 'You Already Know Me' },
}